// Atelier Iris 2: The Azoth of Destiny
// #ID = 19228

function UsedAsInGameCheck() => byte(0x31DA24)
function VoiceLanguageSetting() => byte(0x7DB726)
function CutscenesFlag() => byte(0x7DB788)
function CurrentMainCharacter() => byte(0x7DB798)
function CurrentMoney() => dword(0x7DB79C)
function CurrentPlayTime() => dword(0x7DB7A0)
function MemoryCardAccessor() => dword(0x7DE5D0)
function BattleGamestate() => byte(0x7F530A)
function InBattleIndicator() => byte(0xB27E90)
function CharacterCurrentLevelFelt() => word(0xB29E80)
function CharacterCurrentLifeFelt() => word(0xB29E82)
function CharacterTotalLifeFelt() => word(0xB29E96)
function CharacterCurrentAttackFelt() => word(0xB29E98)
function CharacterCurrentMagicFelt() => word(0xB29E9A)
function CharacterCurrentDefenseFelt() => word(0xB29E9C)
function CharacterCurrentSpeedFelt() => word(0xB29E9E)
function CharacterCurrentFResFelt() => word(0xB29EA0)
function CharacterCurrentIResFelt() => word(0xB29EA2)
function CharacterCurrentLResFelt() => word(0xB29EA4)
function CharacterCurrentDResFelt() => word(0xB29EA6)
function CharacterCurrentExpFelt() => dword(0xB29EA8)
function SkillManaStrikeFelt() => byte(0xB29EAC)
function SkillAuraStrikeFelt() => word(0xB29EB6)
function SkillRagingStrikeFelt() => word(0xB29EBC)
function SkillManaWaveFelt() => byte(0xB29EBF)
function SkillAuraWaveFelt() => word(0xB29EC8)
function SkillRagingWaveFelt() => word(0xB29ECE)
function SkillStrikeEdgeFelt() => word(0xB29ED4)
function SkillPhantomEdgeFelt() => word(0xB29EDA)
function SkillFinalEdgeFelt() => word(0xB29EE0)
function SkillBlueEnergyFelt() => word(0xB29EE6)
function SkillManaWeaponFelt() => word(0xB29EEC)
function SkillManaShieldFelt() => word(0xB29EF2)
function SkillLifeUpFelt() => word(0xB29EF8)
function SkillOffenseFelt() => word(0xB29EFE)
function SkillBlockFelt() => word(0xB29F04)
function SkillMagicUpFelt() => word(0xB29F0A)
function SkillDefenseUpFelt() => word(0xB29F10)
function SkillDefenseFelt() => word(0xB29F16)
function SkillAttackUpFelt() => word(0xB29F1C)
function SkillExperienceUpFelt() => word(0xB29F22)
function SkillSpUpFelt() => word(0xB29F28)
function SkillExtraBlowFelt() => word(0xB29F2E)
function SkillChargeUpFelt() => word(0xB29F34)
function SkillResistUpFelt() => word(0xB29F3A)
function SkillDoubleAttackFelt() => word(0xB29F40)
function SkillSpeedUpFelt() => word(0xB29F46)
function SkillGutsFelt() => word(0xB29F4C)
function SkillKnockbackFelt() => word(0xB29F52)
function CharacterCurrentWeaponFelt() => word(0xB29F54)
function CharacterAccessory1Felt() => word(0xB29F56)
function CharacterAccessory2Felt() => word(0xB29F58)
function CharacterEquipment1Felt() => word(0xB29F5A)
function CharacterEquipment2Felt() => word(0xB29F5C)
function CharacterCurrentLevelViese() => word(0xB29F60)
function CharacterCurrentLifeViese() => word(0xB29F62)
function CharacterTotalLifeViese() => word(0xB29F76)
function CharacterCurrentAttackViese() => word(0xB29F78)
function CharacterCurrentMagicViese() => word(0xB29F7A)
function CharacterCurrentDefenseViese() => word(0xB29F7C)
function CharacterCurrentSpeedViese() => word(0xB29F7E)
function CharacterCurrentFResViese() => word(0xB29F80)
function CharacterCurrentIResViese() => word(0xB29F82)
function CharacterCurrentLResViese() => word(0xB29F84)
function CharacterCurrentDResViese() => word(0xB29F86)
function CharacterCurrentExpViese() => dword(0xB29F88)
function SkillCopperHandHealingViese() => byte(0xB29F8D)
function SkillSilverHandHealingViese() => word(0xB29F96)
function SkillGoldHandHealingViese() => word(0xB29F9C)
function SkillBlessOfRainViese() => word(0xB29FA2)
function SkillHealingDropViese() => word(0xB29FA8)
function SkillHealingRainViese() => word(0xB29FAE)
function SkillElementalExtractionViese() => byte(0xB29FB0)
function SkillWideExtractionViese() => word(0xB29FBA)
function SkillMegaExtractionViese() => word(0xB29FC0)
function SkillWideItemViese() => byte(0xB29FC3)
function SkillPowerItemViese() => word(0xB29FCC)
function SkillLivingItemViese() => word(0xB29FD2)
function SkillOffenseViese() => word(0xB29FD8)
function SkillDefenseViese() => word(0xB29FDE)
function SkillExperienceUpViese() => word(0xB29FE4)
function SkillSpUpViese() => word(0xB29FEA)
function SkillDodgeViese() => word(0xB29FF0)
function SkillAttackUpViese() => word(0xB29FF6)
function SkillMagicGuardViese() => word(0xB29FFC)
function SkillMagicUpViese() => word(0xB2A002)
function SkillSpeedUpViese() => word(0xB2A008)
function SkillResistUpViese() => word(0xB2A00E)
function SkillHealViese() => word(0xB2A014)
function SkillMagicUpViese() => word(0xB2A01A)
function SkillDefenseUpViese() => word(0xB2A020)
function SkillRestoreViese() => word(0xB2A026)
function SkillLifeUpViese() => word(0xB2A02C)
function SkillGutsViese() => word(0xB2A032)
function CharacterCurrentWeaponViese() => word(0xB2A034)
function CharacterAccessory1Viese() => word(0xB2A036)
function CharacterAccessory2Viese() => word(0xB2A038)
function CharacterEquipment1Viese() => word(0xB2A03A)
function CharacterEquipment2Viese() => word(0xB2A03C)
function CharacterCurrentLevelNoin() => word(0xB2A040)
function CharacterCurrentLifeNoin() => word(0xB2A042)
function CharacterTotalLifeNoin() => word(0xB2A056)
function CharacterCurrentAttackNoin() => word(0xB2A058)
function CharacterCurrentMagicNoin() => word(0xB2A05A)
function CharacterCurrentDefenseNoin() => word(0xB2A05C)
function CharacterCurrentSpeedNoin() => word(0xB2A05E)
function CharacterCurrentFResNoin() => word(0xB2A060)
function CharacterCurrentIResNoin() => word(0xB2A062)
function CharacterCurrentLResNoin() => word(0xB2A064)
function CharacterCurrentLResNoin() => word(0xB2A066)
function CharacterCurrentExpNoin() => dword(0xB2A068)
function SkillForceBlastNoin() => byte(0xB2A06D)
function SkillStormBlastNoin() => word(0xB2A076)
function SkillFalconBlastNoin() => word(0xB2A07C)
function SkillComboAttackNoin() => word(0xB2A082)
function SkillFuryComboNoin() => word(0xB2A088)
function SkillNoinComboNoin() => word(0xB2A08E)
function SkillHealBreezeNoin() => byte(0xB2A091)
function SkillHealWindNoin() => word(0xB2A09A)
function SkillGaleHealNoin() => word(0xB2A0A0)
function SkillSuckerKickNoin() => word(0xB2A0A6)
function SkillHealingLightNoin() => word(0xB2A0AC)
function SkillAdrenalineNoin() => word(0xB2A0B2)
function SkillLifeUpNoin() => word(0xB2A0B8)
function SkillDefenseUpNoin() => word(0xB2A0BE)
function SkillDefenseNoin() => word(0xB2A0C4)
function SkillEsperienceUpNoin() => word(0xB2A0CA)
function SkillAttackUpNoin() => word(0xB2A0D0)
function SkillMagicUpNoin() => word(0xB2A0D6)
function SkillOffenseNoin() => word(0xB2A0DC)
function SkillSpUpNoin() => word(0xB2A0E2)
function SkillDouleAttackNoin() => word(0xB2A0E8)
function SkillDodgeNoin() => word(0xB2A0EE)
function SkillResistUpNoin() => word(0xB2A0F4)
function SkillSpeedUpNoin() => word(0xB2A0FA)
function SkillGutsNoin() => word(0xB2A100)
function SkillQuickNoin() => word(0xB2A106)
function SkillKnockbackNoin() => word(0xB2A10C)
function SkillCounterNoin() => word(0xB2A112)
function CharacterCurrentWeaponNoin() => word(0xB2A114)
function CharacterAccessory1Noin() => word(0xB2A116)
function CharacterAccessory2Noin() => word(0xB2A118)
function CharacterEquipment1Noin() => word(0xB2A11A)
function CharacterEquipment2Noin() => word(0xB2A11C)
function CharacterCurrentLevelGray() => word(0xB2A120)
function CharacterCurrentLifeGray() => word(0xB2A122)
function CharacterTotalLifeGray() => word(0xB2A136)
function CharacterCurrentAttackGray() => word(0xB2A138)
function CharacterCurrentMagicGray() => word(0xB2A13A)
function CharacterCurrentDefenseGray() => word(0xB2A13C)
function CharacterCurrentSpeedGray() => word(0xB2A13E)
function CharacterCurrentFResGray() => word(0xB2A140)
function CharacterCurrentIResGray() => word(0xB2A142)
function CharacterCurrentLResGray() => word(0xB2A144)
function CharacterCurrentLResGray() => word(0xB2A146)
function CharacterCurrentExpGray() => dword(0xB2A148)
function SkillTwinDragonGray() => byte(0xB2A14D)
function SkillShreddingDragonGray() => word(0xB2A156)
function SkillDragonRuinGray() => word(0xB2A15C)
function SkillHolyBladeGray() => byte(0xB2A15F)
function SkillFlamingBladeGray() => word(0xB2A168)
function SkillInfernalBladeGray() => word(0xB2A16E)
function SkillTeraFlameGray() => word(0xB2A174)
function SkillTauntGray() => word(0xB2A17A)
function SkillDragonSCryGray() => byte(0xB2A17D)
function SkillFireBreathGray() => byte(0xB2A183)
function SkillIceBreathGray() => word(0xB2A18C)
function SkillThunderBreathGray() => word(0xB2A192)
function SkillOffenseGray() => word(0xB2A198)
function SkillDefenseUpGray() => word(0xB2A19E)
function SkillBlockGray() => word(0xB2A1A4)
function SkillLifeUpGray() => word(0xB2A1AA)
function SkillExperienceUpGray() => word(0xB2A1B0)
function SkillAttackUpGray() => word(0xB2A1B6)
function SkillMagicUpGray() => word(0xB2A1BC)
function SkillDragonSlayerGray() => byte(0xB2A1BE)
function SkillDefenseGray() => word(0xB2A1C8)
function SkillSpUpGray() => word(0xB2A1CE)
function SkillRegenGray() => word(0xB2A1D4)
function SkillChargeUpGray() => word(0xB2A1DA)
function SkillResistUpGray() => word(0xB2A1E0)
function SkillGutsGray() => word(0xB2A1E6)
function SkillSpeedUpGray() => word(0xB2A1EC)
function SkillKnockbackGray() => word(0xB2A1F2)
function CharacterCurrentWeaponGray() => word(0xB2A1F4)
function CharacterAccessory1Gray() => word(0xB2A1F6)
function CharacterAccessory2Gray() => word(0xB2A1F8)
function CharacterEquipment1Gray() => word(0xB2A1FA)
function CharacterEquipment2Gray() => word(0xB2A1FC)
function CharacterCurrentLevelFee() => word(0xB2A200)
function CharacterCurrentLifeFee() => word(0xB2A202)
function CharacterTotalLifeFee() => word(0xB2A216)
function CharacterCurrentAttackFee() => word(0xB2A218)
function CharacterCurrentMagicFee() => word(0xB2A21A)
function CharacterCurrentDefenseFee() => word(0xB2A21C)
function CharacterCurrentSpeedFee() => word(0xB2A21E)
function CharacterCurrentFResFee() => word(0xB2A220)
function CharacterCurrentIResFee() => word(0xB2A222)
function CharacterCurrentLResFee() => word(0xB2A224)
function CharacterCurrentLResFee() => word(0xB2A226)
function CharacterCurrentExpFee() => dword(0xB2A228)
function SkillAirSlicerFee() => byte(0xB2A22C)
function SkillTwinSlicerFee() => word(0xB2A236)
function SkillEndlessBladeFee() => word(0xB2A23C)
function SkillEinZecksclawFee() => byte(0xB2A23F)
function SkillEinZeckslashFee() => word(0xB2A248)
function SkillEinZecksdanceFee() => word(0xB2A24E)
function SkillDivineDrainFee() => word(0xB2A254)
function SkillDivineSealFee() => word(0xB2A25A)
function SkillDivineStunFee() => byte(0xB2A25D)
function SkillShadowEndFee() => word(0xB2A266)
function SkillAvatarFee() => word(0xB2A26C)
function SkillZaleShineFee() => word(0xB2A272)
function SkillAttackUpFee() => word(0xB2A278)
function SkillDefenseUpFee() => word(0xB2A27E)
function SkillMagicUp1Fee() => word(0xB2A284)
function SkillExperienceUpFee() => word(0xB2A28A)
function SkillMagicUpFee() => word(0xB2A290)
function SkillOffenseFee() => word(0xB2A296)
function SkillLifeUpFee() => word(0xB2A29C)
function SkillDefenseFee() => word(0xB2A2A2)
function SkillSpUpFee() => word(0xB2A2A8)
function SkillDodgeFee() => word(0xB2A2AE)
function SkillDoubleAttackFee() => word(0xB2A2B4)
function SkillSpeedUpFee() => word(0xB2A2BA)
function SkillResistUpFee() => word(0xB2A2C0)
function SkillGutsFee() => word(0xB2A2C6)
function SkillQuickFee() => word(0xB2A2CC)
function SkillCounterFee() => word(0xB2A2D2)
function CharacterCurrentWeaponFee() => word(0xB2A2D4)
function CharacterAccessory1Fee() => word(0xB2A2D6)
function CharacterAccessory2Fee() => word(0xB2A2D8)
function CharacterEquipment1Fee() => word(0xB2A2DA)
function CharacterEquipment2Fee() => word(0xB2A2DC)
function CharacterCurrentLevelPoe() => word(0xB2A2E0)
function CharacterCurrentLifePoe() => word(0xB2A2E2)
function CharacterTotalLifePoe() => word(0xB2A2F6)
function CharacterCurrentAttackPoe() => word(0xB2A2F8)
function CharacterCurrentMagicPoe() => word(0xB2A2FA)
function CharacterCurrentDefensePoe() => word(0xB2A2FC)
function CharacterCurrentSpeedPoe() => word(0xB2A2FE)
function CharacterCurrentFResPoe() => word(0xB2A300)
function CharacterCurrentIResPoe() => word(0xB2A302)
function CharacterCurrentLResPoe() => word(0xB2A304)
function CharacterCurrentLResPoe() => word(0xB2A306)
function CharacterCurrentExpPoe() => dword(0xB2A308)
function SkillFunnyBulletPoe() => byte(0xB2A30D)
function SkillMysteryBulletPoe() => word(0xB2A316)
function SkillBulletSurpisePoe() => word(0xB2A31C)
function SkillPoeFirecrackerPoe() => word(0xB2A322)
function SkillPoeDynamitePoe() => word(0xB2A328)
function SkillPoeDynamiteExPoe() => word(0xB2A32E)
function SkillPoeMissilePoe() => byte(0xB2A331)
function SkillPoeMissileMk2Poe() => word(0xB2A33A)
function SkillPoeMissileMk3Poe() => word(0xB2A340)
function SkillRefuelShotPoe() => byte(0xB2A343)
function SkillPoeBazookaPoe() => word(0xB2A34C)
function SkillSlowBulletPoe() => word(0xB2A352)
function SkillOffensePoe() => word(0xB2A358)
function SkillBlockPoe() => word(0xB2A35E)
function SkillAttackUpPoe() => word(0xB2A364)
function SkillDefenseUpPoe() => word(0xB2A36A)
function SkillDefensePoe() => word(0xB2A370)
function SkillLifeUpPoe() => word(0xB2A376)
function SkillExperienceUpPoe() => word(0xB2A37C)
function SkillSpUpPoe() => word(0xB2A382)
function SkillMagicUpPoe() => word(0xB2A388)
function SkillChargeUpPoe() => word(0xB2A38E)
function SkillFeintShotPoe() => word(0xB2A394)
function SkillRegenPoe() => word(0xB2A39A)
function SkillResistUpPoe() => word(0xB2A3A0)
function SkillDoubleAttackPoe() => word(0xB2A3A6)
function SkillSpeedUpPoe() => word(0xB2A3AC)
function SkillGutsPoe() => word(0xB2A3B2)
function CharacterCurrentWeaponPoe() => word(0xB2A3B4)
function CharacterAccessory1Poe() => word(0xB2A3B6)
function CharacterAccessory2Poe() => word(0xB2A3B8)
function CharacterEquipment1Poe() => word(0xB2A3BA)
function CharacterEquipment2Poe() => word(0xB2A3BC)
function ForamationBattleMemberFrontRow() => byte(0xB2A3C0)
function ForamationBattleMemberMidRow() => byte(0xB2A3C4)
function ForamationBattleMemberBackRow() => byte(0xB2A3C8)
function ForamationStandbyMember1() => byte(0xB2A3CC)
function ForamationStandbyMember2() => byte(0xB2A3D0)
function ForamationStandbyMember3() => byte(0xB2A3D4)
function FireElementQuantity() => word(0xB2A400)
function AirElementQuantity() => word(0xB2A402)
function WaterElementQuantity() => word(0xB2A404)
function LightningElementQuantity() => word(0xB2A406)
function DarkElementQuantity() => word(0xB2A408)
function StoneElementQuantity() => word(0xB2A40A)
function WoodElementQuantity() => word(0xB2A40C)
function LifeElementQuantity() => word(0xB2A40E)
function IllusionElementQuantity() => word(0xB2A410)
function SoundElementQuantity() => word(0xB2A412)
function AromaElementQuantity() => word(0xB2A414)
function PoisonElementQuantity() => word(0xB2A416)
function MetalElementQuantity() => word(0xB2A418)
function PactUru() => byte(0xB2A495)
function PactSilwest() => byte(0xB2A496)
function PactNymph() => byte(0xB2A497)
function PactEital() => byte(0xB2A498)
function PactPlua() => byte(0xB2A499)
function PactDiemia() => byte(0xB2A49A)
function PactDour() => byte(0xB2A49B)
function PactAion() => byte(0xB2A49C)
function PactFaustus() => byte(0xB2A49D)
function PactSiren() => byte(0xB2A49E)
function PactJiptus() => byte(0xB2A4A0)
function PactZuvelk() => byte(0xB2A4A1)
function ManaItemListFlagHealHerb() => byte(0xB2A4A2)
function ManaItemListFlagHealJar() => byte(0xB2A4A3)
function ManaItemListFlagFlame() => byte(0xB2A4A4)
function ManaItemListFlagMegaFlame() => byte(0xB2A4A5)
function ManaItemListFlagTerraFlame() => byte(0xB2A4A6)
function ManaItemListFlagCraft() => byte(0xB2A4A7)
function ManaItemListFlagBombIce() => byte(0xB2A4A8)
function ManaItemListFlagLightningRod() => byte(0xB2A4A9)
function ManaItemListFlagThunderRod() => byte(0xB2A4AA)
function ManaItemListFlagHealBulb() => byte(0xB2A4AB)
function ManaItemListFlagCureJar() => byte(0xB2A4AC)
function ManaItemListFlagMeteor() => byte(0xB2A4AD)
function ManaItemListFlagAmanitaNeedle() => byte(0xB2A4AE)
function ManaItemListFlagBasiliskEye() => byte(0xB2A4AF)
function ManaItemListFlagDragonGem() => byte(0xB2A4B0)
function ManaItemListFlagIceComet() => byte(0xB2A4B1)
function ManaItemListFlagFluteOfCerberus() => byte(0xB2A4B2)
function ManaItemListFlagDarkLightningRod() => byte(0xB2A4B3)
function ManaItemListFlagGlobe() => byte(0xB2A4B4)
function ManaItemListFlagAstralGlobe() => byte(0xB2A4B5)
function ManaItemListFlagUnderGlobe() => byte(0xB2A4B6)
function ManaItemListFlagNectar() => byte(0xB2A4B7)
function ManaItemListFlagAltenaJar() => byte(0xB2A4B8)
function ManaItemListFlagRefuel() => byte(0xB2A4B9)
function ManaItemListFlagHuffinWater() => byte(0xB2A4BA)
function ManaItemListFlagDiselement() => byte(0xB2A4BB)
function ManaItemListFlagCureCrystal() => byte(0xB2A4BC)
function ManaItemListFlagAromaPot() => byte(0xB2A4BD)
function ManaItemListFlagFearBottle() => byte(0xB2A4BE)
function ManaItemListFlagPendulum() => byte(0xB2A4BF)
function ManaItemListFlagReturnGem() => byte(0xB2A4C0)
function ManaItemListFlagPhilosophicAsh() => byte(0xB2A4C1)
function ManaItemListFlagUroborusPill() => byte(0xB2A4C2)
function ManaItemListFlagItemWish() => byte(0xB2A4C3)
function ManaItemListFlagElixir() => byte(0xB2A4C4)
function ManaItemListFlagDivineShield() => byte(0xB2A4C5)
function ManaItemListFlagPowerShield() => byte(0xB2A4C6)
function ManaItemListFlagDarkWater() => byte(0xB2A4C7)
function ManaItemListFlagElementBlaze() => byte(0xB2A4C8)
function ManaItemListFlagTimeStone() => byte(0xB2A4C9)
function ManaItemListFlagUni() => byte(0xB2A4CA)
function ManaItemListFlagSuperUni() => byte(0xB2A4CB)
function ManaItemListFlagUruCore() => byte(0xB2A4CC)
function ManaItemListFlagNymphCore() => byte(0xB2A4CD)
function ManaItemListFlagSilwestCore() => byte(0xB2A4CE)
function ManaItemListFlagPluaCore() => byte(0xB2A4CF)
function ManaItemListFlagZuvelkCore() => byte(0xB2A4D0)
function ManaItemListFlagFaustusCore() => byte(0xB2A4D1)
function ManaItemListFlagAionCore() => byte(0xB2A4D2)
function ManaItemListFlagWonderGrow() => byte(0xB2A4D3)
function ManaItemListFlagYugdoreWater() => byte(0xB2A4D4)
function ManaItemListFlagFairyTea() => byte(0xB2A4D5)
function ManaItemListFlagGrapplingHook() => byte(0xB2A4D6)
function ManaItemListFlagGlowLamp() => byte(0xB2A4D7)
function ManaItemListFlagFlayHammer() => byte(0xB2A4D8)
function ManaItemListFlagAnimalCookie() => byte(0xB2A4D9)
function ManaItemListFlagRainbowCloth() => byte(0xB2A4DA)
function ManaItemListFlagDestoneOrb() => byte(0xB2A4DB)
function ManaItemListFlagKeyOfHermes() => byte(0xB2A4DC)
function ManaItemListFlagMegidoSKey() => byte(0xB2A4DD)
function ManaItemListFlagMellOrb() => byte(0xB2A4DE)
function AccessoryItemsFairyClothes() => byte(0xB2A4DF)
function AccessoryItemsFairyHat() => byte(0xB2A4E0)
function AccessoryItemsPigeonBlood() => byte(0xB2A4E1)
function AccessoryItemsAresLiquid() => byte(0xB2A4E2)
function AccessoryItemsSlaithCrown() => byte(0xB2A4E3)
function AccessoryItemsGradinCrown() => byte(0xB2A4E4)
function AccessoryItemsAncientMask() => byte(0xB2A4E5)
function AccessoryItemsTotemShield() => byte(0xB2A4E6)
function AccessoryItemsDragonShield() => byte(0xB2A4E7)
function AccessoryItemsSpiritProtect() => byte(0xB2A4E8)
function AccessoryItemsEdenOutfit() => byte(0xB2A4E9)
function AccessoryItemsRotenHelm() => byte(0xB2A4EA)
function AccessoryItemsBlauHelm() => byte(0xB2A4EB)
function AccessoryItemsSilverArmor() => byte(0xB2A4EC)
function AccessoryItemsPendelook() => byte(0xB2A4ED)
function AccessoryItemsDarkFairyClothes() => byte(0xB2A4EE)
function AccessoryItemsDarkFairyHat() => byte(0xB2A4EF)
function AccessoryItemsSlaithDress() => byte(0xB2A4F0)
function AccessoryItemsMagicPaper() => byte(0xB2A4F1)
function AccessoryItemsDemonRing() => byte(0xB2A4F2)
function AccessoryItemsDragonFangEarring() => byte(0xB2A4F3)
function AccessoryItemsLotaCake() => byte(0xB2A4F4)
function AccessoryItemsPlattin() => byte(0xB2A4F5)
function AccessoryItemsGurguSCane() => byte(0xB2A4F6)
function AccessoryItemsFireBrand() => byte(0xB2A4F7)
function AccessoryItemsIceBrand() => byte(0xB2A4F8)
function AccessoryItemsLightningBrand() => byte(0xB2A4F9)
function AccessoryItemsDazaSBelt() => byte(0xB2A4FA)
function AccessoryItemsGargoylesMirror() => byte(0xB2A4FB)
function AccessoryItemsAnkh() => byte(0xB2A4FC)
function AccessoryItemsMushroomArmor() => byte(0xB2A4FD)
function AccessoryItemsSoulShroud() => byte(0xB2A4FE)
function AccessoryItemsMagicPipe() => byte(0xB2A4FF)
function AccessoryItemsAromaTalisman() => byte(0xB2A500)
function AccessoryItemsNivTiara() => byte(0xB2A501)
function AccessoryItemsDiemaAnkh() => byte(0xB2A502)
function AccessoryItemsIllusionBracelet() => byte(0xB2A503)
function AccessoryItemsAngelFeather() => byte(0xB2A504)
function AccessoryItemsSpeedster() => byte(0xB2A505)
function AccessoryItemsAromaMaterial() => byte(0xB2A506)
function AlchemyItemsBlueBracer() => byte(0xB2A507)
function AlchemyItemsEliteLiqueur() => byte(0xB2A508)
function AlchemyItemsHolyEvergreen() => byte(0xB2A509)
function AlchemyItemsCharcoal() => byte(0xB2A50A)
function AlchemyItemsBelkBlackbelt() => byte(0xB2A50B)
function AlchemyItemsDamaskRing() => byte(0xB2A50C)
function AlchemyItemsCottonCloth() => byte(0xB2A50D)
function AlchemyItemsSilkCloth() => byte(0xB2A50E)
function AlchemyItemsFormalFabric() => byte(0xB2A50F)
function AlchemyItemsCometGem() => byte(0xB2A510)
function AlchemyItemsMagatamaCone() => byte(0xB2A511)
function AlchemyItemsRedCrystal() => byte(0xB2A512)
function AlchemyItemsWhiteCrystal() => byte(0xB2A513)
function AlchemyItemsMagneticCrystal() => byte(0xB2A514)
function AlchemyItemsAlchemistMedal() => byte(0xB2A515)
function AlchemyItemsSagesFeatherPen() => byte(0xB2A516)
function AlchemyItemsCrystaleavy() => byte(0xB2A517)
function AlchemyItemsCrystalite() => byte(0xB2A518)
function AlchemyItemsNauticalCharts() => byte(0xB2A519)
function AlchemyItemsCelestialMap() => byte(0xB2A51A)
function AlchemyItemsDarkScroll() => byte(0xB2A51B)
function AlchemyItemsMoonDrop() => byte(0xB2A51C)
function AlchemyItemsNewMoonDrop() => byte(0xB2A51D)
function AlchemyItemsFogBox() => byte(0xB2A51E)
function AlchemyItemsSilverAcid() => byte(0xB2A51F)
function AlchemyItemsManatini() => byte(0xB2A520)
function AlchemyItemsManaMoebius() => byte(0xB2A521)
function AlchemyItemsGravityCrystal() => byte(0xB2A522)
function AlchemyItemsBloodClay() => byte(0xB2A523)
function AlchemyItemsGrayCrowbar() => byte(0xB2A524)
function AlchemyItemsSilverCrowbar() => byte(0xB2A525)
function AlchemyItemsGoldCrowbar() => byte(0xB2A526)
function AlchemyItemsRotorAnkh() => byte(0xB2A527)
function AlchemyItemsQuicksilverAnkh() => byte(0xB2A528)
function AlchemyItemsSpitefulStone() => byte(0xB2A529)
function AlchemyItemsVieseCharm() => byte(0xB2A52A)
function AlchemyItemsSunAndWindWing() => byte(0xB2A52B)
function AlchemyItemsCueparts() => byte(0xB2A52C)
function AlchemyItemsReptileEgg() => byte(0xB2A52D)
function AlchemyItemsVerdureDoublet() => byte(0xB2A52E)
function AlchemyItemsRubyPrism() => byte(0xB2A52F)
function HarvestedItemsMagiGrass() => byte(0xB2A530)
function HarvestedItemsOldMagiGrass() => byte(0xB2A531)
function HarvestedItemsYadokFungo() => byte(0xB2A532)
function HarvestedItemsOldYadokFungo() => byte(0xB2A533)
function HarvestedItemsAihieFungo() => byte(0xB2A534)
function HarvestedItemsNue() => byte(0xB2A535)
function HarvestedItemsSuperNue() => byte(0xB2A536)
function HarvestedItemsUrob() => byte(0xB2A537)
function HarvestedItemsTingleberry() => byte(0xB2A538)
function HarvestedItemsPearlberry() => byte(0xB2A539)
function HarvestedItemsTataliaCotton() => byte(0xB2A53A)
function HarvestedItemsGlowgrass() => byte(0xB2A53B)
function HarvestedItemsDryGlowgrass() => byte(0xB2A53C)
function HarvestedItemsFreshGlowgrass() => byte(0xB2A53D)
function HarvestedItemsTriffid() => byte(0xB2A53E)
function HarvestedItemsHuffin() => byte(0xB2A53F)
function HarvestedItemsPureWater() => byte(0xB2A540)
function HarvestedItemsFoulWater() => byte(0xB2A541)
function HarvestedItemsGoatMilk() => byte(0xB2A542)
function HarvestedItemsDoreWater() => byte(0xB2A543)
function HarvestedItemsGradenSalt() => byte(0xB2A544)
function HarvestedItemsFlour() => byte(0xB2A545)
function HarvestedItemsWax() => byte(0xB2A546)
function HarvestedItemsAle() => byte(0xB2A547)
function HarvestedItemsRedWine() => byte(0xB2A548)
function HarvestedItemsIndustrialAlcohol() => byte(0xB2A549)
function HarvestedItemsSilverWater() => byte(0xB2A54A)
function HarvestedItemsDragonHorn() => byte(0xB2A54B)
function HarvestedItemsDragonBlood() => byte(0xB2A54C)
function HarvestedItemsRedLegien() => byte(0xB2A54D)
function HarvestedItemsSilverLegien() => byte(0xB2A54E)
function HarvestedItemsOre() => byte(0xB2A54F)
function HarvestedItemsRedOre() => byte(0xB2A550)
function HarvestedItemsLargeRedOre() => byte(0xB2A551)
function HarvestedItemsDemOre() => byte(0xB2A552)
function HarvestedItemsAeronium() => byte(0xB2A553)
function HarvestedItemsLargeAeronium() => byte(0xB2A554)
function HarvestedItemsAncientCore() => byte(0xB2A555)
function HarvestedItemsIceStone() => byte(0xB2A556)
function HarvestedItemsDragonBone() => byte(0xB2A557)
function HarvestedItemsDragonMeat() => byte(0xB2A558)
function HarvestedItemsShadowStone() => byte(0xB2A559)
function HarvestedItemsCometStone() => byte(0xB2A55A)
function HarvestedItemsGravityStone() => byte(0xB2A55B)
function HarvestedItemsLightningStone() => byte(0xB2A55C)
function HarvestedItemsDesertStone() => byte(0xB2A55D)
function HarvestedItemsMoonStone() => byte(0xB2A55E)
function HarvestedItemsWildMeat() => byte(0xB2A55F)
function HarvestedItemsSpoiledMeat() => byte(0xB2A560)
function HarvestedItemsFrozenRain() => byte(0xB2A561)
function HarvestedItemsMiniPendelook() => byte(0xB2A562)
function HarvestedItemsDragonTongue() => byte(0xB2A563)
function HarvestedItemsPhoenixQuill() => byte(0xB2A564)
function HarvestedItemsPuniball() => byte(0xB2A565)
function HarvestedItemsFauxPuniball() => byte(0xB2A566)
function HarvestedItemsString() => byte(0xB2A567)
function HarvestedItemsHexiGlass() => byte(0xB2A568)
function HarvestedItemsPikohammer() => byte(0xB2A569)
function HarvestedItemsGroovecube() => byte(0xB2A56A)
function HarvestedItemsGlobeball() => byte(0xB2A56B)
function HarvestedItemsVioletFungus() => byte(0xB2A56C)
function HarvestedItemsGogoSuit() => byte(0xB2A56D)
function HarvestedItemsRainbowDisc() => byte(0xB2A56E)
function HarvestedItemsStarPiece() => byte(0xB2A56F)
function HarvestedItemsDarkMana() => byte(0xB2A570)
function HarvestedItemsBlackMana() => byte(0xB2A571)
function HarvestedItemsGlowingMana() => byte(0xB2A572)
function HarvestedItemsRedMana() => byte(0xB2A573)
function HarvestedItemsYellowMana() => byte(0xB2A574)
function HarvestedItemsGreenMana() => byte(0xB2A575)
function HarvestedItemsBlueMana() => byte(0xB2A576)
function KeyItemsLibraryPass() => byte(0xB2A577)
function KeyItemsFireGem() => byte(0xB2A578)
function KeyItemsWindGem() => byte(0xB2A579)
function KeyItemsAquaGem() => byte(0xB2A57A)
function KeyItemsLightGem() => byte(0xB2A57B)
function KeyItemsDarkGem() => byte(0xB2A57C)
function KeyItemsStoneGem() => byte(0xB2A57D)
function KeyItemsWoodGem() => byte(0xB2A57E)
function KeyItemsLifeGem() => byte(0xB2A57F)
function KeyItemsDreamGem() => byte(0xB2A580)
function KeyItemsSoundGem() => byte(0xB2A581)
function KeyItemsFloraGem() => byte(0xB2A582)
function KeyItemsPoisonGem() => byte(0xB2A583)
function KeyItemsGoldenGem() => byte(0xB2A584)
function KeyItemsShareRing() => byte(0xB2A585)
function KeyItemsPetroglyphManual() => byte(0xB2A586)
function KeyItemsHalFlower() => byte(0xB2A587)
function KeyItemsVisa() => byte(0xB2A588)
function KeyItemsDowsingGuide() => byte(0xB2A589)
function KeyItemsTolenaSLetter() => byte(0xB2A58A)
function KeyItemsYugenDiaryVol2() => byte(0xB2A58B)
function KeyItemsMirrorOfTwilight() => byte(0xB2A58C)
function KeyItemsLeginSWing() => byte(0xB2A58D)
function KeyItemsElusmusFragment() => byte(0xB2A58E)
function KeyItemsYO17jBlueprints() => byte(0xB2A58F)
function KeyItemsWorkshopMap() => byte(0xB2A590)
function KeyItemsAlchemy101() => byte(0xB2A591)
function KeyItemsWeaponGuide() => byte(0xB2A592)
function KeyItemsGardenBook() => byte(0xB2A593)
function KeyItemsClothspinner() => byte(0xB2A594)
function KeyItemsTheLight() => byte(0xB2A595)
function KeyItemsAntidoteGuide() => byte(0xB2A596)
function KeyItemsTheLife() => byte(0xB2A597)
function KeyItemsAlchemicEcon() => byte(0xB2A598)
function KeyItemsReincarnationRecipe() => byte(0xB2A599)
function KeyItemsYachSNotes() => byte(0xB2A59A)
function KeyItemsManners101() => byte(0xB2A59B)
function KeyItemsMagicSnackRecipe() => byte(0xB2A59C)
function KeyItemsAlchemicHistory() => byte(0xB2A59D)
function KeyItemsSoulGenesis() => byte(0xB2A59E)
function KeyItemsIrisNotes() => byte(0xB2A59F)
function KeyItemsBookOfHermes() => byte(0xB2A5A0)
function KeyItemsBookAlha() => byte(0xB2A5A1)
function KeyItemsChaosDiary() => byte(0xB2A5A2)
function KeyItemsAncientSkills() => byte(0xB2A5A3)
function KeyItemsBookOfMarcus() => byte(0xB2A5A4)
function KeyItemsAlchemicDestiny() => byte(0xB2A5A5)
function KeyItemsBlacksmith101() => byte(0xB2A5A6)
function KeyItemsMythology1() => byte(0xB2A5A7)
function KeyItemsMythology2() => byte(0xB2A5A8)
function KeyItemsBookOfTroth() => byte(0xB2A5A9)
function KeyItemsHealingSkills() => byte(0xB2A5AA)
function KeyItemsMeMyselfBomb() => byte(0xB2A5AB)
function KeyItemsMyUltimateBomb() => byte(0xB2A5AC)
function KeyItemsLumliaTheKnight() => byte(0xB2A5AD)
function KeyItemsBotany101() => byte(0xB2A5AE)
function KeyItemsManaPower() => byte(0xB2A5AF)
function KeyItemsPirateBramus() => byte(0xB2A5B0)
function KeyItemsHeavenEarth() => byte(0xB2A5B1)
function KeyItemsHeavenlySigh() => byte(0xB2A5B2)
function KeyItemsManaPowerPower() => byte(0xB2A5B3)
function KeyItemsInstructionManual() => byte(0xB2A5B4)
function KeyItemsFallenBook() => byte(0xB2A5B5)
function KeyItemsTownHistory() => byte(0xB2A5B6)
function KeyItemsIceAge() => byte(0xB2A5B7)
function KeyItemsEllis() => byte(0xB2A5B8)
function KeyItemsIllusionalVacation() => byte(0xB2A5B9)
function KeyItemsMysticBeast() => byte(0xB2A5BA)
function KeyItemsBelkhyde() => byte(0xB2A5BB)
function KeyItemsMysticalBeast() => byte(0xB2A5BC)
function KeyItemsFairyTales() => byte(0xB2A5BD)
function KeyItemsNoName1() => byte(0xB2A5BE)
function KeyItemsNoName2() => byte(0xB2A5BF)
function KeyItemsBookOfUroborus() => byte(0xB2A5C0)
function KeyItemsSlaithSongs() => byte(0xB2A5C1)
function KeyItemsGeology() => byte(0xB2A5C2)
function KeyItemsBlacksmithAdvanced() => byte(0xB2A5C3)
function KeyItemsVeekTactics() => byte(0xB2A5C4)
function KeyItemsVieseSRecipe() => byte(0xB2A5C5)
function KeyItemsBbq101() => byte(0xB2A5C6)
function KeyItemsJewelOfEden() => byte(0xB2A5C7)
function KeyItemsChurchTale() => byte(0xB2A5C8)
function KeyItemsTikTik() => byte(0xB2A5C9)
function KeyItemsMiracleStone() => byte(0xB2A5CA)
function KeyItemsShiningMetal() => byte(0xB2A5CB)
function KeyItemsNoir() => byte(0xB2A5CC)
function KeyItemsCrystal101() => byte(0xB2A5CD)
function KeyItemsBookOfInfinia() => byte(0xB2A5CE)
function KeyItemsHolyScript() => byte(0xB2A5CF)
function KeyItemsPaperSkills() => byte(0xB2A5D0)
function KeyItemsManners101() => byte(0xB2A5D1)
function KeyItemsExperiment() => byte(0xB2A5D2)
function KeyItemsMellAndTheMonster() => byte(0xB2A5D3)
function KeyItemsRevival() => byte(0xB2A5D4)
function KeyItemsAmanitaSDiary() => byte(0xB2A5D5)
function KeyItemsCursedMan() => byte(0xB2A5D6)
function KeyItemsLiquidification() => byte(0xB2A5D7)
function KeyItemsSlaithHistory() => byte(0xB2A5D8)
function KeyItemsMysticBeast2() => byte(0xB2A5D9)
function KeyItemsDragonSlayerTales() => byte(0xB2A5DA)
function KeyItemsLeneal() => byte(0xB2A5DB)
function KeyItemsLostItem() => byte(0xB2A5DC)
function KeyItemsManaPowerWind() => byte(0xB2A5DD)
function KeyItemsManaPowerDark() => byte(0xB2A5DE)
function KeyItemsManaPowerEvil() => byte(0xB2A5DF)
function KeyItemsManaPowerLife() => byte(0xB2A5E0)
function KeyItemsMilitaryTactics() => byte(0xB2A5E1)
function KeyItemsTheNewElement() => byte(0xB2A5E2)
function KeyItemsSlaithFashion() => byte(0xB2A5E3)
function KeyItemsNekoSWork() => byte(0xB2A5E4)
function KeyItemsStorm() => byte(0xB2A5E5)
function KeyItemsNeokSWork2() => byte(0xB2A5E6)
function KeyItemsIntellect() => byte(0xB2A5E7)
function KeyItemsHopesAndDreams() => byte(0xB2A5E8)
function KeyItemsFairyLife1() => byte(0xB2A5E9)
function KeyItemsFairyLife2() => byte(0xB2A5EA)
function KeyItemsSoulBook() => byte(0xB2A5EB)
function KeyItemsTheBookOfSoil() => byte(0xB2A5EC)
function KeyItemsWeatherReport() => byte(0xB2A5ED)
function CharacterWeaponFeltAzureAzoth() => byte(0xB2A5EE)
function CharacterWeaponFeltFlamingAzoth() => byte(0xB2A5EF)
function CharacterWeaponFeltLightningAzoth() => byte(0xB2A5F0)
function CharacterWeaponFeltGaleAzoth() => byte(0xB2A5F1)
function CharacterWeaponFeltAlloyAzoth() => byte(0xB2A5F2)
function CharacterWeaponFeltDarkAzoth() => byte(0xB2A5F3)
function CharacterWeaponFeltHolyAzoth() => byte(0xB2A5F4)
function CharacterWeaponFeltDivineAzoth() => byte(0xB2A5F5)
function CharacterWeaponFeltSpiritAzoth() => byte(0xB2A5F6)
function CharacterWeaponFeltAegisAzoth() => byte(0xB2A5F7)
function CharacterWeaponFeltRoyalAzoth() => byte(0xB2A5F8)
function CharacterWeaponFeltDestiny() => byte(0xB2A5F9)
function CharacterWeaponVieseAngelStaff() => byte(0xB2A5FA)
function CharacterWeaponVieseFairyStaff() => byte(0xB2A5FB)
function CharacterWeaponViesePrimStaff() => byte(0xB2A5FC)
function CharacterWeaponVieseSorcererSStaff() => byte(0xB2A5FD)
function CharacterWeaponVieseBashingQueen() => byte(0xB2A5FE)
function CharacterWeaponVieseMuteStaff() => byte(0xB2A5FF)
function CharacterWeaponVieseEbonyStaff() => byte(0xB2A600)
function CharacterWeaponVieseSaintStaff() => byte(0xB2A601)
function CharacterWeaponVieseProvidenceStaff() => byte(0xB2A602)
function CharacterWeaponVieseHeavenlyStaff() => byte(0xB2A603)
function CharacterWeaponVieseEarthlyStaff() => byte(0xB2A604)
function CharacterWeaponVieseGoddessStaff() => byte(0xB2A605)
function CharacterWeaponNoinEizenKnuckle() => byte(0xB2A606)
function CharacterWeaponNoinGauntlet() => byte(0xB2A607)
function CharacterWeaponNoinCrystalClaw() => byte(0xB2A608)
function CharacterWeaponNoinLehernKnuckle() => byte(0xB2A609)
function CharacterWeaponNoinPointGetter() => byte(0xB2A60A)
function CharacterWeaponNoinSilverGauntlet() => byte(0xB2A60B)
function CharacterWeaponNoinMeteorGauntlet() => byte(0xB2A60C)
function CharacterWeaponNoinManaGlove() => byte(0xB2A60D)
function CharacterWeaponNoinMajinGauntlet() => byte(0xB2A60E)
function CharacterWeaponNoinHolyBandages() => byte(0xB2A60F)
function CharacterWeaponNoinGodspeedFist() => byte(0xB2A610)
function CharacterWeaponNoinHolyBattleFist() => byte(0xB2A611)
function CharacterWeaponGrayDragonKiller() => byte(0xB2A612)
function CharacterWeaponGrayEnduranceBlade() => byte(0xB2A613)
function CharacterWeaponGrayIceBlade() => byte(0xB2A614)
function CharacterWeaponGrayThunderBlade() => byte(0xB2A615)
function CharacterWeaponGrayVacuumBlade() => byte(0xB2A616)
function CharacterWeaponGrayCrystalBlade() => byte(0xB2A617)
function CharacterWeaponGrayPassionBlade() => byte(0xB2A618)
function CharacterWeaponGrayRoadringBlade() => byte(0xB2A619)
function CharacterWeaponGrayInvincibleBlade() => byte(0xB2A61A)
function CharacterWeaponGrayWarriorBlade() => byte(0xB2A61B)
function CharacterWeaponGrayRagingGod() => byte(0xB2A61C)
function CharacterWeaponFeeAssassinScythe() => byte(0xB2A61D)
function CharacterWeaponFeeCrossSlicer() => byte(0xB2A61E)
function CharacterWeaponFeeNightinggale() => byte(0xB2A61F)
function CharacterWeaponFeeBrightSickle() => byte(0xB2A620)
function CharacterWeaponFeeSoulSlicer() => byte(0xB2A621)
function CharacterWeaponFeeSpiritScythe() => byte(0xB2A622)
function CharacterWeaponFeeShadowSickle() => byte(0xB2A623)
function CharacterWeaponFeeRageSlicer() => byte(0xB2A624)
function CharacterWeaponFeeChaosSickle() => byte(0xB2A625)
function CharacterWeaponFeeAltenaScythe() => byte(0xB2A626)
function CharacterWeaponFeePhotonSaber() => byte(0xB2A627)
function CharacterWeaponPoeFairyPistol() => byte(0xB2A628)
function CharacterWeaponPoeParallelmite() => byte(0xB2A629)
function CharacterWeaponPoePoeSAutomatic() => byte(0xB2A62A)
function CharacterWeaponPoePoeCannon() => byte(0xB2A62B)
function CharacterWeaponPoePipoteRifle() => byte(0xB2A62C)
function CharacterWeaponPoeParallelmite2() => byte(0xB2A62D)
function CharacterWeaponPoePistolMark3() => byte(0xB2A62E)
function CharacterWeaponPoeGatlingGun() => byte(0xB2A62F)
function CharacterWeaponPoeFairyPukoref() => byte(0xB2A630)
function CharacterWeaponPoePoeBlaster7() => byte(0xB2A631)
function CharacterWeaponPoeSurgeCannon() => byte(0xB2A632)
function CharacterWeaponPoePoeMagnumSp() => byte(0xB2A633)
function BitflagMonsterListFlagPuni() => byte(0xB2A634)
function BitflagMonsterListFlagMiniPuni() => byte(0xB2A635)
function BitflagMonsterListFlagGiantPuni() => byte(0xB2A636)
function BitflagMonsterListFlagIcePuni() => byte(0xB2A637)
function BitflagMonsterListFlagRedPuni() => byte(0xB2A638)
function BitflagMonsterListFlagGoldenPuni() => byte(0xB2A639)
function BitflagMonsterListFlagFauxPuni() => byte(0xB2A63A)
function BitflagMonsterListFlagZombiePuni() => byte(0xB2A63B)
function BitflagMonsterListFlagPuniQueen() => byte(0xB2A63C)
function BitflagMonsterListFlagSuperPuni() => byte(0xB2A63D)
function BitflagMonsterListFlagMountainPig() => byte(0xB2A63E)
function BitflagMonsterListFlagBabyPig() => byte(0xB2A63F)
function BitflagMonsterListFlagSrMountainPig() => byte(0xB2A640)
function BitflagMonsterListFlagWolf() => byte(0xB2A641)
function BitflagMonsterListFlagCerberus() => byte(0xB2A642)
function BitflagMonsterListFlagWolfLeader() => byte(0xB2A643)
function BitflagMonsterListFlagSupremeWolf() => byte(0xB2A644)
function BitflagMonsterListFlagFalconHawk() => byte(0xB2A645)
function BitflagMonsterListFlagVulture() => byte(0xB2A646)
function BitflagMonsterListFlagRoc() => byte(0xB2A647)
function BitflagMonsterListFlagSunEagle() => byte(0xB2A648)
function BitflagMonsterListFlagMandragora() => byte(0xB2A649)
function BitflagMonsterListFlagVineTrap() => byte(0xB2A64A)
function BitflagMonsterListFlagFlyTrapper() => byte(0xB2A64B)
function BitflagMonsterListFlagTriffid() => byte(0xB2A64C)
function BitflagMonsterListFlagCacto() => byte(0xB2A64D)
function BitflagMonsterListFlagWoodGolem() => byte(0xB2A64E)
function BitflagMonsterListFlagStoneGolem() => byte(0xB2A64F)
function BitflagMonsterListFlagSentry() => byte(0xB2A650)
function BitflagMonsterListFlagSalamander() => byte(0xB2A651)
function BitflagMonsterListFlagBasilisk() => byte(0xB2A652)
function BitflagMonsterListFlagFrozard() => byte(0xB2A653)
function BitflagMonsterListFlagTotem() => byte(0xB2A654)
function BitflagMonsterListFlagTotemite() => byte(0xB2A655)
function BitflagMonsterListFlagWitch() => byte(0xB2A656)
function BitflagMonsterListFlagGhost() => byte(0xB2A657)
function BitflagMonsterListFlagLanternJack() => byte(0xB2A658)
function BitflagMonsterListFlagPhantom() => byte(0xB2A659)
function BitflagMonsterListFlagMasterPuni() => byte(0xB2A65A)
function BitflagMonsterListFlagMonsterPiig() => byte(0xB2A65B)
function BitflagMonsterListFlagBrownie() => byte(0xB2A65C)
function BitflagMonsterListFlagAssassinDoll() => byte(0xB2A65D)
function BitflagMonsterListFlagJin() => byte(0xB2A65E)
function BitflagMonsterListFlagMadBrownie() => byte(0xB2A65F)
function BitflagMonsterListFlagMurderBot() => byte(0xB2A660)
function BitflagMonsterListFlagWereCat() => byte(0xB2A661)
function BitflagMonsterListFlagHellKitty() => byte(0xB2A662)
function BitflagMonsterListFlagEvilBeast() => byte(0xB2A663)
function BitflagMonsterListFlagWildCat() => byte(0xB2A664)
function BitflagMonsterListFlagThief() => byte(0xB2A665)
function BitflagMonsterListFlagRogue() => byte(0xB2A666)
function BitflagMonsterListFlagMasterThief() => byte(0xB2A667)
function BitflagMonsterListFlagMercenary() => byte(0xB2A668)
function BitflagMonsterListFlagHeavyMetal() => byte(0xB2A669)
function BitflagMonsterListFlagImperialFootman() => byte(0xB2A66A)
function BitflagMonsterListFlagImperialCommander() => byte(0xB2A66B)
function BitflagMonsterListFlagGeneral() => byte(0xB2A66C)
function BitflagMonsterListFlagGunner() => byte(0xB2A66D)
function BitflagMonsterListFlagArcher() => byte(0xB2A66E)
function BitflagMonsterListFlagImperialArcher() => byte(0xB2A66F)
function BitflagMonsterListFlagBeastMaster() => byte(0xB2A670)
function BitflagMonsterListFlagBanshee() => byte(0xB2A671)
function BitflagMonsterListFlagElemental() => byte(0xB2A672)
function BitflagMonsterListFlagSuccubus() => byte(0xB2A673)
function BitflagMonsterListFlagLilm() => byte(0xB2A674)
function BitflagMonsterListFlagBlazeElement() => byte(0xB2A675)
function BitflagMonsterListFlagNocturneElement() => byte(0xB2A676)
function BitflagMonsterListFlagFrigidElement() => byte(0xB2A677)
function BitflagMonsterListFlagShockElement() => byte(0xB2A678)
function BitflagMonsterListFlagMaxwell() => byte(0xB2A679)
function BitflagMonsterListFlagBugbear() => byte(0xB2A67A)
function BitflagMonsterListFlagCharon() => byte(0xB2A67B)
function BitflagMonsterListFlagElda() => byte(0xB2A67C)
function BitflagMonsterListFlagVirum() => byte(0xB2A67D)
function BitflagMonsterListFlagFlameVirum() => byte(0xB2A67E)
function BitflagMonsterListFlagUniVirum() => byte(0xB2A67F)
function BitflagMonsterListFlagMegaVirum() => byte(0xB2A680)
function BitflagMonsterListFlagVirumZombie() => byte(0xB2A681)
function BitflagMonsterListFlagNecroHydra() => byte(0xB2A682)
function BitflagMonsterListFlagBaphy() => byte(0xB2A683)
function BitflagMonsterListFlagLegion() => byte(0xB2A684)
function BitflagMonsterListFlagBaal() => byte(0xB2A685)
function BitflagMonsterListFlagShadowLegion() => byte(0xB2A686)
function BitflagMonsterListFlagImperialSoldier() => byte(0xB2A687)
function BitflagMonsterListFlagReliefSoldier() => byte(0xB2A688)
function BitflagMonsterListFlagImperialGuard() => byte(0xB2A689)
function BitflagMonsterListFlagImperialSupportSoldier() => byte(0xB2A68A)
function BitflagMonsterListFlagDeathKnight() => byte(0xB2A68B)
function BitflagMonsterListFlagDeathWarrior() => byte(0xB2A68C)
function BitflagMonsterListFlagDeathGigas() => byte(0xB2A68D)
function BitflagMonsterListFlagVorpalSword() => byte(0xB2A68E)
function BitflagMonsterListFlagRhinoBeast() => byte(0xB2A68F)
function BitflagMonsterListFlagHammerhead() => byte(0xB2A690)
function BitflagMonsterListFlagStonehead() => byte(0xB2A691)
function BitflagMonsterListFlagArmadillo() => byte(0xB2A692)
function BitflagMonsterListFlagCaterpillar() => byte(0xB2A693)
function BitflagMonsterListFlagFiredillo() => byte(0xB2A694)
function BitflagMonsterListFlagPoisonousFungo() => byte(0xB2A695)
function BitflagMonsterListFlagParafungo() => byte(0xB2A696)
function BitflagMonsterListFlagFungo() => byte(0xB2A697)
function BitflagMonsterListFlagFungoKing() => byte(0xB2A698)
function BitflagMonsterListFlagNecromancer() => byte(0xB2A699)
function BitflagMonsterListFlagEnchantress() => byte(0xB2A69A)
function BitflagMonsterListFlagSorceress() => byte(0xB2A69B)
function BitflagMonsterListFlagMahouShouju() => byte(0xB2A69C)
function BitflagMonsterListFlagHarpy() => byte(0xB2A69D)
function BitflagMonsterListFlagShadowgirl() => byte(0xB2A69E)
function BitflagMonsterListFlagDarkwing() => byte(0xB2A69F)
function BitflagMonsterListFlagSandfish() => byte(0xB2A6A0)
function BitflagMonsterListFlagSandDragon() => byte(0xB2A6A1)
function BitflagMonsterListFlagFloatingFish() => byte(0xB2A6A2)
function BitflagMonsterListFlagMudEater() => byte(0xB2A6A3)
function BitflagMonsterListFlagGuardian() => byte(0xB2A6A4)
function BitflagMonsterListFlagElderVirum() => byte(0xB2A6A5)
function BitflagMonsterListFlagBookEater() => byte(0xB2A6A6)
function BitflagMonsterListFlagPurpleManaCluster() => byte(0xB2A6A8)
function BitflagMonsterListFlagGreenmanaCluster() => byte(0xB2A6A9)
function BitflagMonsterListFlagRedManaCluster() => byte(0xB2A6AA)
function BitflagMonsterListFlagClockwerk() => byte(0xB2A6AB)
function BitflagMonsterListFlagPuniKing() => byte(0xB2A6B3)
function BitflagMonsterListFlagPuniKnight() => byte(0xB2A6B4)
function BitflagMonsterListFlagPuniPunist() => byte(0xB2A6B5)
function BitflagMonsterListFlagPuniPrincess() => byte(0xB2A6B6)
function BitflagMonsterListFlagSlaithSReincarnation() => byte(0xB2A6C0)
function BitflagMonsterListFlagGalahad() => byte(0xB2A6C2)
function BitflagMonsterListFlagQuetzalcoatl() => byte(0xB2A6C3)
function BitflagMonsterListFlagChaos() => byte(0xB2A6C4)
function BitflagMonsterListFlagEvilServant() => byte(0xB2A6C5)
function BitflagMonsterListFlagArgdelavald() => byte(0xB2A6C6)
function BitflagMonsterListFlagPalaxius() => byte(0xB2A6C7)
function BitflagMonsterListFlagInstantBrownie() => byte(0xB2A6C9)
function BitflagMonsterListFlagPuniRider() => byte(0xB2A6CA)
function BitflagMonsterListFlagAmalgem() => byte(0xB2A6CB)
function BitflagMonsterListFlagSuncoatl() => byte(0xB2A6CC)
function BitflagMonsterListFlagSkycoatl() => byte(0xB2A6CD)
function BitflagMonsterListFlagElekicoatl() => byte(0xB2A6CE)
function BitflagMonsterListFlagEmeraldPuni() => byte(0xB2A6CF)
function BitflagMonsterListFlagHellLegion() => byte(0xB2A6D0)
function BitflagMonsterListFlagHellSlayer() => byte(0xB2A6D1)
function BitflagMonsterListFlagMushroomPrince() => byte(0xB2A6D2)
function BitflagMonsterListFlagShade() => byte(0xB2A6D3)
function BitflagMonsterListFlagLightPrincess() => byte(0xB2A6D4)
function BitflagMonsterListFlagDarkPrincess() => byte(0xB2A6D5)
function BitflagMonsterListFlagSnowmaiden() => byte(0xB2A6D6)
function BitflagMonsterListFlagNightAroma() => byte(0xB2A6D7)
function BitflagMonsterListFlagUndergroundQueen() => byte(0xB2A6D8)
function BitflagMonsterListFlagBlazeElement() => byte(0xB2A6D9)
function BitflagMonsterListFlagDragonia() => byte(0xB2A6DA)
function BitflagMonsterListFlagDivineGuard() => byte(0xB2A6DB)
function BitflagMonsterListFlagDivineJudge() => byte(0xB2A6DC)
function ReferenceSkillListOffense() => byte(0xB2A6DD)
function ReferenceSkillListKnockback() => byte(0xB2A6DE)
function ReferenceSkillListChargeUp() => byte(0xB2A6DF)
function ReferenceSkillListDoubleAttack() => byte(0xB2A6E0)
function ReferenceSkillListDefense() => byte(0xB2A6E1)
function ReferenceSkillListBlock() => byte(0xB2A6E2)
function ReferenceSkillListCounter() => byte(0xB2A6E3)
function ReferenceSkillListGuts() => byte(0xB2A6E4)
function ReferenceSkillListRestore() => byte(0xB2A6E5)
function ReferenceSkillListExtraBlow() => byte(0xB2A6E6)
function ReferenceSkillListMagicUp() => byte(0xB2A6E7)
function ReferenceSkillListMagicGuard() => byte(0xB2A6E8)
function ReferenceSkillListDodge() => byte(0xB2A6E9)
function ReferenceSkillListHeal() => byte(0xB2A6EA)
function ReferenceSkillListQuick() => byte(0xB2A6EB)
function ReferenceSkillListDragonSlayer() => byte(0xB2A6EC)
function ReferenceSkillListRegen() => byte(0xB2A6ED)
function ReferenceSkillListFeintShot() => byte(0xB2A6EE)
function ReferenceSkillListExperienceUp() => byte(0xB2A6EF)
function ReferenceSkillListSpUp() => byte(0xB2A6F0)
function ReferenceSkillListLifeUp() => byte(0xB2A6F1)
function ReferenceSkillListAttackUp() => byte(0xB2A6F2)
function ReferenceSkillListDefenseUp() => byte(0xB2A6F3)
function ReferenceSkillListSpeedUp() => byte(0xB2A6F4)
function ReferenceSkillListMagicUp() => byte(0xB2A6F5)
function ReferenceSkillListResistUp() => byte(0xB2A6F6)
function PeopleListNoin() => byte(0xB2A6F7)
function PeopleListGray() => byte(0xB2A6F8)
function PeopleListFee() => byte(0xB2A6F9)
function PeopleListPoe() => byte(0xB2A6FA)
function PeopleListIris() => byte(0xB2A6FB)
function PeopleListKreuz() => byte(0xB2A6FC)
function PeopleListEizlenHighPriest() => byte(0xB2A6FD)
function PeopleListChaos() => byte(0xB2A6FE)
function PeopleListGalahad() => byte(0xB2A6FF)
function PeopleListTolena() => byte(0xB2A700)
function PeopleListTheodore() => byte(0xB2A701)
function PeopleListMax() => byte(0xB2A702)
function PeopleListYuveria() => byte(0xB2A703)
function PeopleListMeila() => byte(0xB2A704)
function PeopleListMitsue() => byte(0xB2A705)
function PeopleListHagel() => byte(0xB2A706)
function PeopleListTheresa() => byte(0xB2A707)
function PeopleListYach() => byte(0xB2A708)
function PeopleListKlavia() => byte(0xB2A709)
function PeopleListLutanus() => byte(0xB2A70A)
function PeopleListMelona() => byte(0xB2A70B)
function ReferenceLettersDearFelt() => byte(0xB2A729)
function ReferenceLettersWhatASurprise() => byte(0xB2A72A)
function ReferenceLettersIMSoRelieved() => byte(0xB2A72B)
function ReferenceLettersInRiesevelt() => byte(0xB2A72C)
function ReferenceLettersISentTheHuffin() => byte(0xB2A72D)
function ReferenceLettersAzothNews() => byte(0xB2A72E)
function ReferenceLettersBelkhyde() => byte(0xB2A72F)
function ReferenceLettersTheSea() => byte(0xB2A730)
function ReferenceLettersINeedACureJar() => byte(0xB2A731)
function ReferenceLettersIMPrayingForHer() => byte(0xB2A732)
function ReferenceLettersThereAre2Azoths() => byte(0xB2A733)
function ReferenceLettersGreatNews() => byte(0xB2A734)
function ReferenceLettersEdenSSecret() => byte(0xB2A735)
function ReferenceLettersMapOfBelkhyde() => byte(0xB2A736)
function ReferenceLettersDamagedWorkshop() => byte(0xB2A737)
function ReferenceLettersTheGreatTreeIsBack() => byte(0xB2A738)
function ReferenceLettersTheMistyWorkshop() => byte(0xB2A739)
function ReferenceLettersTheLithographs() => byte(0xB2A73A)
function ReferenceLettersOurFamily() => byte(0xB2A73B)
function ReferenceLettersOfCourse() => byte(0xB2A73C)
function ReferenceLettersThankYou() => byte(0xB2A73D)
function ReferenceLettersWithJiptus() => byte(0xB2A73E)
function ReferenceLettersGrand() => byte(0xB2A73F)
function ReferenceLettersDragonSlaying() => byte(0xB2A740)
function ReferenceLettersHermes() => byte(0xB2A741)
function ReferenceLettersKeyOfHermes() => byte(0xB2A742)
function ReferenceLettersNelvia() => byte(0xB2A743)
function ReferenceLettersWeathervaneHill() => byte(0xB2A744)
function ReferenceLettersImperialCampBattle() => byte(0xB2A745)
function ReferenceLettersACharm() => byte(0xB2A746)
function ReferenceLettersTheInformation() => byte(0xB2A747)
function ReferenceLettersSorryToWorryYou() => byte(0xB2A748)
function ReferenceLettersIUnderstand() => byte(0xB2A749)
function ReferenceLettersVictoryDefeat() => byte(0xB2A74A)
function ReferenceLettersAReasonForEveryEvil() => byte(0xB2A74B)
function ReferenceLettersThatSTerrible() => byte(0xB2A74C)
function ReferenceLettersRestoringEden() => byte(0xB2A74D)
function ReferenceLettersIWillWait() => byte(0xB2A74E)
function ReferenceLettersAfterTheBattle() => byte(0xB2A74F)
function ReviewListEleCostDownXs() => byte(0xB2A7A3)
function ReviewListDelSupportX1() => byte(0xB2A7A4)
function ReviewListQualityUpXs() => byte(0xB2A7A5)
function ReviewListDamageUpXs() => byte(0xB2A7A6)
function ReviewListHealUpXs() => byte(0xB2A7A7)
function ReviewListLifeUpXs() => byte(0xB2A7A8)
function ReviewListPwrUpXs() => byte(0xB2A7A9)
function ReviewListDefUpXs() => byte(0xB2A7AA)
function ReviewListMagicUpXs() => byte(0xB2A7AB)
function ReviewListSpdUpXs() => byte(0xB2A7AC)
function ReviewListFResUpXs() => byte(0xB2A7AD)
function ReviewListIResUpXs() => byte(0xB2A7AE)
function ReviewListLResUpXs() => byte(0xB2A7AF)
function ReviewListDResUpXs() => byte(0xB2A7B0)
function ReviewListAllResUpXs() => byte(0xB2A7B1)
function ReviewListFDamageS() => byte(0xB2A7B2)
function ReviewListIDamageS() => byte(0xB2A7B3)
function ReviewListLDamageS() => byte(0xB2A7B4)
function ReviewListDDamageS() => byte(0xB2A7B5)
function ReviewListHrzRangeS() => byte(0xB2A7B6)
function ReviewListVerRangeS() => byte(0xB2A7B7)
function ReviewListRangeS() => byte(0xB2A7B8)
function ReviewListAttack1() => byte(0xB2A7B9)
function ReviewListCriticalUpS() => byte(0xB2A7BA)
function ReviewListMagicCriticalUpS() => byte(0xB2A7BB)
function ReviewListEleCostDownS() => byte(0xB2A7BC)
function ReviewListDelSupportX2() => byte(0xB2A7BD)
function ReviewListQualityUpS() => byte(0xB2A7BE)
function ReviewListDamageUpS() => byte(0xB2A7BF)
function ReviewListHealUpS() => byte(0xB2A7C0)
function ReviewListLifeUpS() => byte(0xB2A7C1)
function ReviewListPwrUpS() => byte(0xB2A7C2)
function ReviewListDefUpS() => byte(0xB2A7C3)
function ReviewListMagicUpS() => byte(0xB2A7C4)
function ReviewListSpdUpS() => byte(0xB2A7C5)
function ReviewListFResUpS() => byte(0xB2A7C6)
function ReviewListIResUpS() => byte(0xB2A7C7)
function ReviewListLResUpS() => byte(0xB2A7C8)
function ReviewListDResUpS() => byte(0xB2A7C9)
function ReviewListAllResUpS() => byte(0xB2A7CA)
function ReviewListFDamageM() => byte(0xB2A7CB)
function ReviewListIDamageM() => byte(0xB2A7CC)
function ReviewListLDamageM() => byte(0xB2A7CD)
function ReviewListDDamageM() => byte(0xB2A7CE)
function ReviewListHrzRangeM() => byte(0xB2A7CF)
function ReviewListVerRangeM() => byte(0xB2A7D0)
function ReviewListRangeM() => byte(0xB2A7D1)
function ReviewListAttack2() => byte(0xB2A7D2)
function ReviewListCriticalUpM() => byte(0xB2A7D3)
function ReviewListMagicCriticalUpM() => byte(0xB2A7D4)
function ReviewListEleCostDownM() => byte(0xB2A7D5)
function ReviewListQualityUpM() => byte(0xB2A7D6)
function ReviewListDamageUpM() => byte(0xB2A7D7)
function ReviewListHealUpM() => byte(0xB2A7D8)
function ReviewListLifeUpM() => byte(0xB2A7D9)
function ReviewListPwrUpM() => byte(0xB2A7DA)
function ReviewListDefUpM() => byte(0xB2A7DB)
function ReviewListMagicUpM() => byte(0xB2A7DC)
function ReviewListSpdUpM() => byte(0xB2A7DD)
function ReviewListFResUpM() => byte(0xB2A7DE)
function ReviewListIResUpM() => byte(0xB2A7DF)
function ReviewListLResUpM() => byte(0xB2A7E0)
function ReviewListDResUpM() => byte(0xB2A7E1)
function ReviewListAllResUpM() => byte(0xB2A7E2)
function ReviewListFDamageL() => byte(0xB2A7E3)
function ReviewListIDamageL() => byte(0xB2A7E4)
function ReviewListLDamageL() => byte(0xB2A7E5)
function ReviewListDDamageL() => byte(0xB2A7E6)
function ReviewListHrzRangeL() => byte(0xB2A7E7)
function ReviewListVerRangeL() => byte(0xB2A7E8)
function ReviewListRangeL() => byte(0xB2A7E9)
function ReviewListAttack3() => byte(0xB2A7EA)
function ReviewListCriticalUpL() => byte(0xB2A7EB)
function ReviewListMagicCriticalUpL() => byte(0xB2A7EC)
function ReviewListEleCostDownL() => byte(0xB2A7ED)
function ReviewListQualityUpL() => byte(0xB2A7EE)
function ReviewListDamageUpL() => byte(0xB2A7EF)
function ReviewListHealUpL() => byte(0xB2A7F0)
function ReviewListLifeUpL() => byte(0xB2A7F1)
function ReviewListPwrUpL() => byte(0xB2A7F2)
function ReviewListDefUpL() => byte(0xB2A7F3)
function ReviewListMagicUpL() => byte(0xB2A7F4)
function ReviewListSpdUpL() => byte(0xB2A7F5)
function ReviewListFResUpL() => byte(0xB2A7F6)
function ReviewListIResUpL() => byte(0xB2A7F7)
function ReviewListLResUpL() => byte(0xB2A7F8)
function ReviewListDResUpL() => byte(0xB2A7F9)
function ReviewListAllResUpL() => byte(0xB2A7FA)
function ReviewListFDamageXl() => byte(0xB2A7FB)
function ReviewListIDamageXl() => byte(0xB2A7FC)
function ReviewListLDamageXl() => byte(0xB2A7FD)
function ReviewListDDamageXl() => byte(0xB2A7FE)
function ReviewListAttack4() => byte(0xB2A7FF)
function ReviewListEleCostDownXl() => byte(0xB2A800)
function ReviewListQualityUpXl() => byte(0xB2A801)
function ReviewListDamageUpXl() => byte(0xB2A802)
function ReviewListHealUpXl() => byte(0xB2A803)
function ReviewListLifeUpXl() => byte(0xB2A804)
function ReviewListPwrUpXl() => byte(0xB2A805)
function ReviewListDefUpXl() => byte(0xB2A806)
function ReviewListMagicUpXl() => byte(0xB2A807)
function ReviewListSpdUpXl() => byte(0xB2A808)
function ReviewListFResUpXl() => byte(0xB2A809)
function ReviewListIResUpXl() => byte(0xB2A80A)
function ReviewListLResUpXl() => byte(0xB2A80B)
function ReviewListDResUpXl() => byte(0xB2A80C)
function ReviewListAllResUpXl() => byte(0xB2A80D)
function ReviewListElementalDamage() => byte(0xB2A80E)
function ReviewListPuniSlayer() => byte(0xB2A80F)
function ReviewListBeastBuster() => byte(0xB2A810)
function ReviewListDragonSlayer() => byte(0xB2A811)
function ReviewListDemonSlayer() => byte(0xB2A812)
function ReviewListManaSlayer() => byte(0xB2A813)
function ReviewListEvilSlayer() => byte(0xB2A814)
function ReviewListParalysisAttack() => byte(0xB2A815)
function ReviewListPoisonAttack() => byte(0xB2A816)
function ReviewListCurseAttack() => byte(0xB2A817)
function ReviewListSleepAttack() => byte(0xB2A818)
function ReviewListExtremePoisonAttack() => byte(0xB2A819)
function ReviewListCursedPower() => byte(0xB2A81A)
function ReviewListExtractMagicPower() => byte(0xB2A81B)
function ReviewListMagicalPower() => byte(0xB2A81C)
function ReviewListSkySonata() => byte(0xB2A81D)
function ReviewListWindWaltz() => byte(0xB2A81E)
function ReviewListHighConcentration() => byte(0xB2A81F)
function ReviewListHolyPower() => byte(0xB2A820)
function ReviewListForbiddenPower() => byte(0xB2A821)
function ReviewListBlessedPower() => byte(0xB2A822)
function ReviewListDivinePower() => byte(0xB2A823)
function MapLocationsUnlocked() => byte(0xB2A824)
function PrimaryLoadSlotCurrentEpisode() => dword(0xB2A8B8)
function CurrentLocation() => byte(0xB2A8D4)
function OverworldIndicator() => byte(0xB2A8D5)
function CurrentMapLocation() => word(0xB30D3C)
function EventFlagNewGameStarted() => byte(0xB38CD0)
function EventFlagIntroBattleCutSceneCompleted() => byte(0xB38CD8)
function EventFlagEpisode1SpokeToLutanusAndReceivedAlchemy101() => byte(0xB38CE0)
function EventFlagEpisode1LeftEdenTempleCutscene() => byte(0xB38CE8)
function EventFlagEpisode1VieseHasCheckedIfFeltWasHome() => byte(0xB38CF0)
function EventFlagEpisode1VieseMetUpWithFeltAtBelkhydeGate() => byte(0xB38D00)
function EventFlagEpisode1FeltAndVieseEnterMarmelForest() => byte(0xB38D10)
function EventFlagEpisode1FeltAndVieseApproachTheAzothForTheFirstTime() => byte(0xB38D30)
function EventFlagEpisode1FeltTriesPullingOutTheAzoth() => byte(0xB38D38)
function EventFlagEpisode1FeltAndVieseApproachDourSGreatTree() => byte(0xB38D48)
function EventFlagEpisode1VieseAndFeltConvoWhenLeavingTheGreatTreeAreaCutscene() => byte(0xB38D50)
function EventFlagEpisode1TheAzothSpeaksToFelt() => byte(0xB38D58)
function EventFlagEpisode1FeltPullsOutTheAzoth() => byte(0xB38D60)
function EventFlagEpisode1FeltAndVieseReturnToEdenTempleToReportTheTreeMissing() => byte(0xB38D70)
function EventFlagEpisode1FeltAndVieseInformKreuz() => byte(0xB38D78)
function EventFlagEpisode1ReturnedToBelkhydeGateAfterInformingKreuz() => byte(0xB38D90)
function EventFlagEpisode1DourPopsIntoTheWorkshopWithViese() => byte(0xB38DA0)
function EventFlagEpisode1FirstSynthesis() => byte(0xB38DB0)
function EventFlagEpisode1FeltSpeaksToKreuzAfterBelkhydeGateOpens() => byte(0xB38DB8)
function EventFlagEpisode1FeltEntersBelkhydeGate() => byte(0xB38DC0)
function EventFlagEpisode2CutsceneAndDialoguePostEpisode1() => byte(0xB38DC8)
function EventFlagEpisode2FirstWildBattleEncounter() => byte(0xB38DD0)
function EventFlagEpisode2DialogueAfterLeavingDesertArea1() => byte(0xB38DD8)
function EventFlagEpisode2FeltDialogueAboutGottaKeepMoving() => byte(0xB38DE0)
function EventFlagEpisode2DialogueAfterEnteringOasis() => byte(0xB38DE8)
function EventFlagEpisode2RememberingVieseDialogueWakingUpInTent() => byte(0xB38DF0)
function EventFlagEpisode2LeaveTentAndNoinJoinsTheParty() => byte(0xB38DF8)
function EventFlagEpisode2SpeakToNoinAboutTheEdenAndTheGate() => byte(0xB38E00)
function EventFlagEpisode2EnteredTatalliaVillage() => byte(0xB38E08)
function EventFlagEpisode2DialogueWithMitsueShopInTatalliaVillage() => byte(0xB38E18)
function EventFlagEpisode2EnteredTatalliaMayorTentMayorDialogue() => byte(0xB38E20)
function EventFlagEpisode2EnteredDesertRuinsAndSpiedOnChaos() => byte(0xB38E28)
function EventFlagEpisode2CameUponTheSoldiersInTheDesertRuins() => byte(0xB38E30)
function EventFlagEpisode2PostBattleWithSoldiers() => byte(0xB38E38)
function EventFlagEpisode2OpenedChestDialogueAboutCraftingRecipes() => byte(0xB38E40)
function EventFlagEpisode2StartingToLeaveTheRuinWhereSoldiersWereTalkToAzothSword() => byte(0xB38E50)
function EventFlagEpisode2ReturnedFromRuinsToTatalliaVillage() => byte(0xB38E58)
function EventFlagEpisode2EventDialogueInDesertForkSandstorm() => byte(0xB38E60)
function EventFlagEpisode2EnteredCampInSandstorm() => byte(0xB38E68)
function EventFlagEpisode2CanTLeaveTentGottaWaitItOut() => byte(0xB38E70)
function EventFlagEpisode2DialogueInTentDuringSandstorm() => byte(0xB38E78)
function EventFlagEpisode2UsedBookChangeoverToViese() => byte(0xB38E80)
function EventFlagEpisode3VieseDialogueWithinTheWorkshopShareRingStartOfEpisode3() => byte(0xB38E88)
function EventFlagEpisode1AttemptedToEnterGreatCaveWithoutKreuzPermission() => byte(0xB38E90)
function EventFlagEpisode3VieseDialogueAboutTheLibraryDoorBeingLockedInEden() => byte(0xB38E98)
function EventFlagEpisode3LeftWorkshopDialogueWithNymphFunnyICanSeeMyHouseFromHere() => byte(0xB38EA0)
function EventFlagEpisode3VieseDialogueFindingLutanusInNourCityShoppingReceivedLibraryPass() => byte(0xB38EA8)
function EventFlagEpisode3VieseDialogueUsedLibraryCardForLibraryInEden() => byte(0xB38EB0)
function EventFlagEpisode3VieseDialogueFoundReceivedPetroglyphManual() => byte(0xB38EB8)
function EventFlagEpisode3VieseDialogueWithPoeAfterLeavingEdenSLibraryPoeTryingToDataViese() => byte(0xB38EC0)
function EventFlagEpisode3VieseDialogueEnteredWorkshopAfterLeavingEden() => byte(0xB38EC8)
function EventFlagEpisode3VieseDialogueEnteredGreatCaveForMetalManaGotKreuzPermissionToEnter() => byte(0xB38ED0)
function EventFlagEpisode3VieseDialogueFlashbackOfMeetingLittleGirl() => byte(0xB38ED8)
function EventFlagEpisode3VieseDialogueLittleGirlPointsVieseToMetalMana() => byte(0xB38EE0)
function EventFlagEpisode3VieseDialogueMakePactWithMetalManaReceiveMarkOfTheMetalMana() => byte(0xB38EE8)
function EventFlagEpisode3VieseDialogueIrisLeavesPartyAndCave() => byte(0xB38EF8)
function EventFlagEpisode3VieseDialogueReturnedToWorkshopAfterPactWithMetalManaPoeMelonaTalkActivateShareRing() => byte(0xB38F00)
function EventFlagEpisode3VieseDialogueCheckedItemsMenueInformedToCreateCraft() => byte(0xB38F10)
function EventFlagEpisode3VieseDialogueCreatedCraft() => byte(0xB38F18)
function EventFlagEpisode4VieseDialogueAboutNoteTranferBackToFeltLearnToSwitch() => byte(0xB38F20)
function EventFlagEpisode3VieseDialogueWithMeila() => byte(0xB38F28)
function EventFlagEpisode3FeltAndNoinDialogueEnterWestRegenbogen() => byte(0xB38F30)
function EventFlagEpisode3FeltAndNoinDialogueSpeakingToImperialSoldierAtWestRegenbogen() => byte(0xB38F38)
function EventFlagEpisode3FeltAndNoinDialogueAboutToEnterRieseveltCity() => byte(0xB38F40)
function EventFlagEpisode3FeltAndNoinDialogueSpokeToBartenderInTheCity() => byte(0xB38F48)
function EventFlagEpisode1AttemptedToEnterCastleButItSDark() => byte(0xB391E8)
function EventFlagEpisode2TatallianGuyWarnsAboutGreatDesert() => byte(0xB394F8)
function EventFlagEpisode1VieseTriesToDoAlchemyButShouldBeDoingSomethingElse() => byte(0xB39508)
function EventFlagEpisode2DialogueAboutHowToAttackGhostEnemies() => byte(0xB3A600)
function ManaItemHealHerb() => byte(0xB3AE30)
function ManaItemHealJar() => byte(0xB3AE44)
function ManaItemFlame() => byte(0xB3AE58)
function ManaItemMegaFlame() => byte(0xB3AE6C)
function ManaItemTeraFlame() => byte(0xB3AE80)
function ManaItemCraft() => byte(0xB3AE94)
function ManaItemBombIce() => byte(0xB3AEA8)
function ManaItemLightningRod() => byte(0xB3AEBC)
function ManaItemThunderRod() => byte(0xB3AED0)
function ManaItemHealBulb() => byte(0xB3AEE4)
function ManaItemCureJar() => byte(0xB3AEF8)
function ManaItemMeteor() => byte(0xB3AF0C)
function ManaItemAmanitaNeedle() => byte(0xB3AF20)
function ManaItemBasiliskEye() => byte(0xB3AF34)
function ManaItemDragonGem() => byte(0xB3AF48)
function ManaItemIceComet() => byte(0xB3AF5C)
function ManaItemFluteOfCerberus() => byte(0xB3AF70)
function ManaItemDarkLightiningCloud() => byte(0xB3AF84)
function ManaItemGlobe() => byte(0xB3AF98)
function ManaItemAstralGlobe() => byte(0xB3AFAC)
function ManaItemUnderGlobe() => byte(0xB3AFC0)
function ManaItemNectar() => byte(0xB3AFD4)
function ManaItemAltenaJar() => byte(0xB3AFE8)
function ManaItemRefuel() => byte(0xB3AFFC)
function ManaItemHuffinWater() => byte(0xB3B010)
function ManaItemDiselement() => byte(0xB3B024)
function ManaItemCureCrystal() => byte(0xB3B038)
function ManaItemAromaPot() => byte(0xB3B04C)
function ManaItemFearBottle() => byte(0xB3B060)
function ManaItemPendulum() => byte(0xB3B074)
function ManaItemReturnGem() => byte(0xB3B088)
function ManaItemPhilosophicAsh() => byte(0xB3B09C)
function ManaItemUroborusPill() => byte(0xB3B0B0)
function ManaItemItemWish() => byte(0xB3B0C4)
function ManaItemElixir() => byte(0xB3B0D8)
function ManaItemDivineShield() => byte(0xB3B0EC)
function ManaItemPowerShield() => byte(0xB3B100)
function ManaItemDarkWater() => byte(0xB3B114)
function ManaItemElementBlaze() => byte(0xB3B128)
function ManaItemTimeStone() => byte(0xB3B13C)
function ManaItemUni() => byte(0xB3B150)
function ManaItemSuperUni() => byte(0xB3B164)
function ManaItemUruCore() => byte(0xB3B178)
function ManaItemNymphCore() => byte(0xB3B18C)
function ManaItemSilwestCore() => byte(0xB3B1A0)
function ManaItemPluaCore() => byte(0xB3B1B4)
function ManaItemZuvelkCore() => byte(0xB3B1C8)
function ManaItemFaustusCore() => byte(0xB3B1DC)
function ManaItemAionCore() => byte(0xB3B1F0)
function ManaItemWonderGrow() => byte(0xB3B204)
function ManaItemYugdoreWater() => byte(0xB3B218)
function ManaItemFairyTea() => byte(0xB3B22C)
function ManaItemGrapplingHook() => byte(0xB3B240)
function ManaItemGlowLamp() => byte(0xB3B254)
function ManaItemFlyHammer() => byte(0xB3B268)
function ManaItemAnimalCookie() => byte(0xB3B27C)
function ManaItemRainbowCloth() => byte(0xB3B290)
function ManaItemDestoneOrb() => byte(0xB3B2A4)
function ManaItemKeyOfHermes() => byte(0xB3B2B8)
function ManaItemMegidoSKey() => byte(0xB3B2CC)
function ManaItemMellOrb() => byte(0xB3B2E0)
function AccessoryItemFairyCloths() => byte(0xB3B2F4)
function AccessoryItemFairyHat() => byte(0xB3B308)
function AccessoryItemPigeonBlood() => byte(0xB3B31C)
function AccessoryItemAresLiquid() => byte(0xB3B330)
function AccessoryItemSlaithCrown() => byte(0xB3B344)
function AccessoryItemGradinCape() => byte(0xB3B358)
function AccessoryItemAncientMask() => byte(0xB3B36C)
function AccessoryItemTotemShield() => byte(0xB3B380)
function AccessoryItemDragonShield() => byte(0xB3B394)
function AccessoryItemSpiritProtect() => byte(0xB3B3A8)
function AccessoryItemEdenOutfit() => byte(0xB3B3BC)
function AccessoryItemRotenHelm() => byte(0xB3B3D0)
function AccessoryItemBlauHelm() => byte(0xB3B3E4)
function AccessoryItemSilverArmor() => byte(0xB3B3F8)
function AccessoryItemPendelook() => byte(0xB3B40C)
function AccessoryItemDarkFairyClothes() => byte(0xB3B420)
function AccessoryItemDarkDairyHat() => byte(0xB3B434)
function AccessoryItemSlaithDress() => byte(0xB3B448)
function AccessoryItemMagicPaper() => byte(0xB3B45C)
function AccessoryItemDemonRing() => byte(0xB3B470)
function AccessoryItemDragonFangEarring() => byte(0xB3B484)
function AccessoryItemLotaCake() => byte(0xB3B498)
function AccessoryItemPlatiin() => byte(0xB3B4AC)
function AccessoryItemGurguSCane() => byte(0xB3B4C0)
function AccessoryItemFireBrand() => byte(0xB3B4D4)
function AccessoryItemIceBrand() => byte(0xB3B4E8)
function AccessoryItemLightningBrand() => byte(0xB3B4FC)
function AccessoryItemDazaSBelt() => byte(0xB3B510)
function AccessoryItemGargoylesMirror() => byte(0xB3B524)
function AccessoryItemAnkh() => byte(0xB3B538)
function AccessoryItemMushroomArmor() => byte(0xB3B54C)
function AccessoryItemSoulShroud() => byte(0xB3B560)
function AccessoryItemMagicPipe() => byte(0xB3B574)
function AccessoryItemAromaTalisman() => byte(0xB3B588)
function AccessoryItemNivTiara() => byte(0xB3B59C)
function AccessoryItemDiemaAnkh() => byte(0xB3B5B0)
function AccessoryItemIllusionBracelet() => byte(0xB3B5C4)
function AccessoryItemAngelFeather() => byte(0xB3B5D8)
function AccessoryItemSpeedster() => byte(0xB3B5EC)
function AccessoryItemAromaMaterial() => byte(0xB3B600)
function AlchemyItemBlueBracer() => byte(0xB3B614)
function AlchemyItemEliteLiqueur() => byte(0xB3B628)
function AlchemyItemHolyEvergreen() => byte(0xB3B63C)
function AlchemyItemCharcoal() => byte(0xB3B650)
function AlchemyItemBelkBlackbelt() => byte(0xB3B664)
function AlchemyItemDamaskRing() => byte(0xB3B678)
function AlchemyItemCottonCloth() => byte(0xB3B68C)
function AlchemyItemSilkCloth() => byte(0xB3B6A0)
function AlchemyItemFormalFabric() => byte(0xB3B6B4)
function AlchemyItemCometGem() => byte(0xB3B6C8)
function AlchemyItemMagatamaCone() => byte(0xB3B6DC)
function AlchemyItemRedCrystal() => byte(0xB3B6F0)
function AlchemyItemWhiteCrystal() => byte(0xB3B704)
function AlchemyItemMagneticCrystal() => byte(0xB3B718)
function AlchemyItemAlchemistMedal() => byte(0xB3B72C)
function AlchemyItemSagesFeatherPen() => byte(0xB3B740)
function AlchemyItemCrystaleavy() => byte(0xB3B754)
function AlchemyItemCrystalite() => byte(0xB3B768)
function AlchemyItemNauticalCharts() => byte(0xB3B77C)
function AlchemyItemCelestrialMap() => byte(0xB3B790)
function AlchemyItemDarkScroll() => byte(0xB3B7A4)
function AlchemyItemMoonDrop() => byte(0xB3B7B8)
function AlchemyItemNewMoonDrop() => byte(0xB3B7CC)
function AlchemyItemFogBox() => byte(0xB3B7E0)
function AlchemyItemSilverAcid() => byte(0xB3B7F4)
function AlchemyItemManatini() => byte(0xB3B808)
function AlchemyItemManaMoebius() => byte(0xB3B81C)
function AlchemyItemGravityCrystal() => byte(0xB3B830)
function AlchemyItemBloodClay() => byte(0xB3B844)
function AlchemyItemGrayCrowbar() => byte(0xB3B858)
function AlchemyItemSilverCrowbar() => byte(0xB3B86C)
function AlchemyItemGoldCrowbar() => byte(0xB3B880)
function AlchemyItemRotorAnkh() => byte(0xB3B894)
function AlchemyItemQuicksilverAnkh() => byte(0xB3B8A8)
function AlchemyItemSpitefulStone() => byte(0xB3B8BC)
function AlchemyItemVieseCharm() => byte(0xB3B8D0)
function AlchemyItemSunAndWindWing() => byte(0xB3B8E4)
function AlchemyItemCueparts() => byte(0xB3B8F8)
function AlchemyItemReptileEgg() => byte(0xB3B90C)
function AlchemyItemVerdueDoublet() => byte(0xB3B920)
function AlchemyItemRubyPrism() => byte(0xB3B934)
function TotalItemsHarvestedItemMagiGrass() => word(0xB3B948)
function TotalItemsHarvestedItemOldMariGrass() => word(0xB3B95C)
function TotalItemsHarvestedItemYadokFungo() => word(0xB3B970)
function TotalItemsHarvestedItemOldYadokFungo() => word(0xB3B984)
function TotalItemsHarvestedItemAihieFungo() => word(0xB3B998)
function TotalItemsHarvestedItemNue() => word(0xB3B9AC)
function TotalItemsHarvestedItemSuperNue() => word(0xB3B9C0)
function TotalItemsHarvestedItemUrob() => word(0xB3B9D4)
function TotalItemsHarvestedItemTingleberry() => word(0xB3B9E8)
function TotalItemsHarvestedItemPearlberry() => word(0xB3B9FC)
function TotalItemsHarvestedItemTataliaCotton() => word(0xB3BA10)
function TotalItemsHarvestedItemGlowgrass() => word(0xB3BA24)
function TotalItemsHarvestedItemDryGlowgrass() => word(0xB3BA38)
function TotalItemsHarvestedItemFreshGlowgrass() => word(0xB3BA4C)
function TotalItemsHarvestedItemTriffid() => word(0xB3BA60)
function TotalItemsHarvestedItemHuffin() => word(0xB3BA74)
function TotalItemsHarvestedItemPureWater() => word(0xB3BA88)
function TotalItemsHarvestedItemFoulWater() => word(0xB3BA9C)
function TotalItemsHarvestedItemGoatMilk() => word(0xB3BAB0)
function TotalItemsHarvestedItemDoreWater() => word(0xB3BAC4)
function TotalItemsHarvestedItemGradenSalt() => word(0xB3BAD8)
function TotalItemsHarvestedItemFlour() => word(0xB3BAEC)
function TotalItemsHarvestedItemWax() => word(0xB3BB00)
function TotalItemsHarvestedItemAle() => word(0xB3BB14)
function TotalItemsHarvestedItemRedWine() => word(0xB3BB28)
function TotalItemsHarvestedItemIndustrialAlcohol() => word(0xB3BB3C)
function TotalItemsHarvestedItemSilverWater() => word(0xB3BB50)
function TotalItemsHarvestedItemDraonHorn() => word(0xB3BB64)
function TotalItemsHarvestedItemDragonBlood() => word(0xB3BB78)
function TotalItemsHarvestedItemRedLegien() => word(0xB3BB8C)
function TotalItemsHarvestedItemSilverLegien() => word(0xB3BBA0)
function TotalItemsHarvestedItemOre() => word(0xB3BBB4)
function TotalItemsHarvestedItemRedOre() => word(0xB3BBC8)
function TotalItemsHarvestedItemLargeRedOre() => word(0xB3BBDC)
function TotalItemsHarvestedItemDemOre() => word(0xB3BBF0)
function TotalItemsHarvestedItemAeroinium() => word(0xB3BC04)
function TotalItemsHarvestedItemLargeAeronium() => word(0xB3BC18)
function TotalItemsHarvestedItemAncientOre() => word(0xB3BC2C)
function TotalItemsHarvestedItemIceStone() => word(0xB3BC40)
function TotalItemsHarvestedItemDragonBone() => word(0xB3BC54)
function TotalItemsHarvestedItemDragonMeat() => word(0xB3BC68)
function TotalItemsHarvestedItemShadowStone() => word(0xB3BC7C)
function TotalItemsHarvestedItemCometStone() => word(0xB3BC90)
function TotalItemsHarvestedItemGravityStone() => word(0xB3BCA4)
function TotalItemsHarvestedItemLightningStone() => word(0xB3BCB8)
function TotalItemsHarvestedItemDesertFlower() => word(0xB3BCCC)
function TotalItemsHarvestedItemMoonStone() => word(0xB3BCE0)
function TotalItemsHarvestedItemWildMeat() => word(0xB3BCF4)
function TotalItemsHarvestedItemSpoiledMeat() => word(0xB3BD08)
function TotalItemsHarvestedItemFrozenRain() => word(0xB3BD1C)
function TotalItemsHarvestedItemMiniPendelook() => word(0xB3BD30)
function TotalItemsHarvestedItemDragonTongue() => word(0xB3BD44)
function TotalItemsHarvestedItemPhoenixQuill() => word(0xB3BD58)
function TotalItemsHarvestedItemPuniball() => word(0xB3BD6C)
function TotalItemsHarvestedItemFauxPuniball() => word(0xB3BD80)
function TotalItemsHarvestedItemString() => word(0xB3BD94)
function TotalItemsHarvestedItemHexiGlass() => word(0xB3BDA8)
function TotalItemsHarvestedItemPikohammer() => word(0xB3BDBC)
function TotalItemsHarvestedItemGroovecube() => word(0xB3BDD0)
function TotalItemsHarvestedItemGloveball() => word(0xB3BDE4)
function TotalItemsHarvestedItemVioletFungus() => word(0xB3BDF8)
function TotalItemsHarvestedItemGogoSuit() => word(0xB3BE0C)
function TotalItemsHarvestedItemRainbowDisc() => word(0xB3BE20)
function TotalItemsHarvestedItemStarPiece() => word(0xB3BE34)
function TotalItemsHarvestedItemDarkMana() => word(0xB3BE48)
function TotalItemsHarvestedItemBlackMana() => word(0xB3BE5C)
function TotalItemsHarvestedItemGlowingMana() => word(0xB3BE70)
function TotalItemsHarvestedItemRedMana() => word(0xB3BE84)
function TotalItemsHarvestedItemYellowMana() => word(0xB3BE98)
function TotalItemsHarvestedItemGreenMana() => word(0xB3BEAC)
function TotalItemsHarvestedItemBlueMana() => word(0xB3BEC0)
function TotalItemsKeyItemLibraryPass() => word(0xB3BED4)
function TotalItemsKeyItemFireGem() => word(0xB3BEE8)
function TotalItemsKeyItemWindGem() => word(0xB3BEFC)
function TotalItemsKeyItemAquaGem() => word(0xB3BF10)
function TotalItemsKeyItemLightGem() => word(0xB3BF24)
function TotalItemsKeyItemDarkGem() => word(0xB3BF38)
function TotalItemsKeyItemStoneGem() => word(0xB3BF4C)
function TotalItemsKeyItemWoodGem() => word(0xB3BF60)
function TotalItemsKeyItemLifeGem() => word(0xB3BF74)
function TotalItemsKeyItemDreamGem() => word(0xB3BF88)
function TotalItemsKeyItemSoundGem() => word(0xB3BF9C)
function TotalItemsKeyItemFloraGem() => word(0xB3BFB0)
function TotalItemsKeyItemPoisonGem() => word(0xB3BFC4)
function TotalItemsKeyItemGoldenGem() => word(0xB3BFD8)
function TotalItemsKeyItemShareRing() => word(0xB3BFEC)
function TotalItemsKeyItemPetroglyphManual() => word(0xB3C000)
function TotalItemsKeyItemHalFlower() => word(0xB3C014)
function TotalItemsKeyItemVisa() => word(0xB3C028)
function TotalItemsKeyItemDowsingGuide() => word(0xB3C03C)
function TotalItemsKeyItemTolenaSLetter() => word(0xB3C050)
function TotalItemsKeyItemYugenDiaryVol2() => word(0xB3C064)
function TotalItemsKeyItemMirrorOfTwilight() => word(0xB3C078)
function TotalItemsKeyItemLeginSWing() => word(0xB3C08C)
function TotalItemsKeyItemElusmusFragment() => word(0xB3C0A0)
function YO17jBlueprints() => byte(0xB3C0B4)
function TotalItemsKeyItemWorkshopMap() => word(0xB3C0C8)
function TotalItemsKeyItemAlchemy101() => word(0xB3C0DC)
function TotalItemsKeyItemWeaponGuide() => word(0xB3C0F0)
function TotalItemsKeyItemGardenBook() => word(0xB3C104)
function TotalItemsKeyItemClothspinner() => word(0xB3C118)
function TotalItemsKeyItemTheLight() => word(0xB3C12C)
function TotalItemsKeyItemTheLife() => word(0xB3C140)
function TotalItemsKeyItemTheLife() => word(0xB3C154)
function TotalItemsKeyItemAlchemicEcon() => word(0xB3C168)
function TotalItemsKeyItemReincarnationRecipe() => word(0xB3C17C)
function TotalItemsKeyItemYachSNotes() => word(0xB3C190)
function TotalItemsKeyItemManners101() => word(0xB3C1A4)
function TotalItemsKeyItemMagicSnackRecipe() => word(0xB3C1B8)
function TotalItemsKeyItemAlchemicHistory() => word(0xB3C1CC)
function TotalItemsKeyItemSoulGenesis() => word(0xB3C1E0)
function TotalItemsKeyItemIrisNotes() => word(0xB3C1F4)
function TotalItemsKeyItemBookOfHermes() => word(0xB3C208)
function TotalItemsKeyItemBookAlha() => word(0xB3C21C)
function TotalItemsKeyItemChaosDiary() => word(0xB3C230)
function TotalItemsKeyItemAncientSkills() => word(0xB3C244)
function TotalItemsKeyItemBookOfMarcus() => word(0xB3C258)
function TotalItemsKeyItemAlchemicDestiny() => word(0xB3C26C)
function TotalItemsKeyItemBlacksmith101() => word(0xB3C280)
function TotalItemsKeyItemMythology1() => word(0xB3C294)
function TotalItemsKeyItemMythology2() => word(0xB3C2A8)
function TotalItemsKeyItemBookOfTroth() => word(0xB3C2BC)
function TotalItemsKeyItemHealingSkills() => word(0xB3C2D0)
function TotalItemsKeyItemMeMyselfBomb() => word(0xB3C2E4)
function TotalItemsKeyItemMyUltimateBomb() => word(0xB3C2F8)
function TotalItemsKeyItemLimliaTheKnight() => word(0xB3C30C)
function TotalItemsKeyItemBotany101() => word(0xB3C320)
function TotalItemsKeyItemManaPower() => word(0xB3C334)
function TotalItemsKeyItemPirateBramus() => word(0xB3C348)
function TotalItemsKeyItemHeavenEarth() => word(0xB3C35C)
function TotalItemsKeyItemHeavenlySigh() => word(0xB3C370)
function TotalItemsKeyItemManaPowerPower() => word(0xB3C384)
function TotalItemsKeyItemInstructionManual() => word(0xB3C398)
function TotalItemsKeyItemFallenBook() => word(0xB3C3AC)
function TotalItemsKeyItemTownHistory() => word(0xB3C3C0)
function TotalItemsKeyItemIceAge() => word(0xB3C3D4)
function TotalItemsKeyItemEllis() => word(0xB3C3E8)
function TotalItemsKeyItemIllusionalVacation() => word(0xB3C3FC)
function TotalItemsKeyItemMysticBeast() => word(0xB3C410)
function TotalItemsKeyItemBelkhyde() => word(0xB3C424)
function TotalItemsKeyItemMysticalBeast() => word(0xB3C438)
function TotalItemsKeyItemFairyTales() => word(0xB3C44C)
function TotalItemsKeyItemNoName1() => word(0xB3C460)
function TotalItemsKeyItemNoName2() => word(0xB3C474)
function TotalItemsKeyItemBookOfUroborus() => word(0xB3C488)
function TotalItemsKeyItemSlaithSongs() => word(0xB3C49C)
function TotalItemsKeyItemGeology() => word(0xB3C4B0)
function TotalItemsKeyItemBlacksmithAdvanced() => word(0xB3C4C4)
function TotalItemsKeyItemVeekTactics() => word(0xB3C4D8)
function TotalItemsKeyItemVieseSRecipe() => word(0xB3C4EC)
function TotalItemsKeyItemBbq101() => word(0xB3C500)
function TotalItemsKeyItemJewelOfEden() => word(0xB3C514)
function TotalItemsKeyItemChurchTale() => word(0xB3C528)
function TotalItemsKeyItemTikTik() => word(0xB3C53C)
function TotalItemsKeyItemMiracleStone() => word(0xB3C550)
function TotalItemsKeyItemShiningMetal() => word(0xB3C564)
function TotalItemsKeyItemNoir() => word(0xB3C578)
function TotalItemsKeyItemCrystal101() => word(0xB3C58C)
function TotalItemsKeyItemBookOfInfinia() => word(0xB3C5A0)
function TotalItemsKeyItemHolyScript() => word(0xB3C5B4)
function TotalItemsKeyItemPaperSkills() => word(0xB3C5C8)
function TotalItemsKeyItemManners101() => word(0xB3C5DC)
function TotalItemsKeyItemExperiment() => word(0xB3C5F0)
function TotalItemsKeyItemMellAndTheMonster() => word(0xB3C604)
function TotalItemsKeyItemAmanitaSDiary() => word(0xB3C62C)
function TotalItemsKeyItemCursedMan() => word(0xB3C640)
function TotalItemsKeyItemLiquidification() => word(0xB3C654)
function TotalItemsKeyItemSaithHistory() => word(0xB3C668)
function TotalItemsKeyItemMysticBeast2() => word(0xB3C67C)
function TotalItemsKeyItemDragonSlayerTales() => word(0xB3C690)
function TotalItemsKeyItemLeneal() => word(0xB3C6A4)
function TotalItemsKeyItemLostItem() => word(0xB3C6B8)
function TotalItemsKeyItemManaPowerWind() => word(0xB3C6CC)
function TotalItemsKeyItemManaPowerDark() => word(0xB3C6E0)
function TotalItemsKeyItemManaPowerEvil() => word(0xB3C6F4)
function TotalItemsKeyItemManaPowerLife() => word(0xB3C708)
function TotalItemsKeyItemMilitaryTactics() => word(0xB3C71C)
function TotalItemsKeyItemTheNewElement() => word(0xB3C730)
function TotalItemsKeyItemSlaithFashion() => word(0xB3C744)
function TotalItemsKeyItemNekoSWork() => word(0xB3C758)
function TotalItemsKeyItemStorm() => word(0xB3C76C)
function TotalItemsKeyItemNekoSWork2() => word(0xB3C780)
function TotalItemsKeyItemIntellect() => word(0xB3C794)
function TotalItemsKeyItemHopesAndDreams() => word(0xB3C7A8)
function TotalItemsKeyItemFairyLife1() => word(0xB3C7BC)
function TotalItemsKeyItemFairyLife2() => word(0xB3C7D0)
function TotalItemsKeyItemSoulBook() => word(0xB3C7E4)
function TotalItemsKeyItemTheBookOfSoil() => word(0xB3C7F8)
function TotalItemsKeyItemWeatherReport() => word(0xB3C80C)
function WeaponBuildFeltAzureAzoth() => byte(0xB3C820)
function WeaponBuildFeltFlamingAzoth() => byte(0xB3C834)
function WeaponBuildFeltLightningAzoth() => byte(0xB3C848)
function WeaponBuildFeltGaleAzoth() => byte(0xB3C85C)
function WeaponBuildFeltAlloyAzoth() => byte(0xB3C870)
function WeaponBuildFeltDarkAzoth() => byte(0xB3C884)
function WeaponBuildFeltHolyAzoth() => byte(0xB3C898)
function WeaponBuildFeltDivineAzoth() => byte(0xB3C8AC)
function WeaponBuildFeltSpiritAzoth() => byte(0xB3C8C0)
function WeaponBuildFeltAegisAzoth() => byte(0xB3C8D4)
function WeaponBuildFeltRoyalAzoth() => byte(0xB3C8E8)
function WeaponBuildFeltDestiny() => byte(0xB3C8FC)
function WeaponBuildVieseAngelStaff() => byte(0xB3C910)
function WeaponBuildVieseFairyStaff() => byte(0xB3C924)
function WeaponBuildViesePrimStaff() => byte(0xB3C938)
function WeaponBuildVieseSorcererSStaff() => byte(0xB3C94C)
function WeaponBuildVieseBashingQueen() => byte(0xB3C960)
function WeaponBuildVieseMuteStaff() => byte(0xB3C974)
function WeaponBuildVieseEbonyStaff() => byte(0xB3C988)
function WeaponBuildVieseSaintStaff() => byte(0xB3C99C)
function WeaponBuildVieseProvidenceStaff() => byte(0xB3C9B0)
function WeaponBuildVieseHeavenlyStaff() => byte(0xB3C9C4)
function WeaponBuildVieseEarthlyStaff() => byte(0xB3C9D8)
function WeaponBuildVieseGoddessStaff() => byte(0xB3C9EC)
function WeaponBuildNoinEizenKnuckle() => byte(0xB3CA00)
function WeaponBuildNoinGauntlet() => byte(0xB3CA14)
function WeaponBuildNoinCrystalClaw() => byte(0xB3CA28)
function WeaponBuildNoinLehernKnuckle() => byte(0xB3CA3C)
function WeaponBuildNoinPointGetter() => byte(0xB3CA50)
function WeaponBuildNoinSilverGauntlet() => byte(0xB3CA64)
function WeaponBuildNoinMeteorGauntlet() => byte(0xB3CA78)
function WeaponBuildNoinManaGlove() => byte(0xB3CA8C)
function WeaponBuildNoinMajinGauntlet() => byte(0xB3CAA0)
function WeaponBuildNoinHolyBandages() => byte(0xB3CAB4)
function WeaponBuildNoinGodspeedFist() => byte(0xB3CAC8)
function WeaponBuildNoinHolyBattleFist() => byte(0xB3CADC)
function WeaponBuildGrayDragonKiller() => byte(0xB3CAF0)
function WeaponBuildGrayEnduranceBlade() => byte(0xB3CB04)
function WeaponBuildGrayIceBlade() => byte(0xB3CB18)
function WeaponBuildGrayThunderBlade() => byte(0xB3CB2C)
function WeaponBuildGrayVaccumBlade() => byte(0xB3CB40)
function WeaponBuildGrayCrystalBlade() => byte(0xB3CB54)
function WeaponBuildGrayPassionBlade() => byte(0xB3CB68)
function WeaponBuildGrayRoaringBlade() => byte(0xB3CB7C)
function WeaponBuildGrayInvincibleBlade() => byte(0xB3CB90)
function WeaponBuildGrayWarriorBlade() => byte(0xB3CBA4)
function WeaponBuildGrayRagingGod() => byte(0xB3CBB8)
function WeaponBuildFeeAssassinScythe() => byte(0xB3CBCC)
function WeaponBuildFeeCrossSlicer() => byte(0xB3CBE0)
function WeaponBuildFeeNightinggale() => byte(0xB3CBF4)
function WeaponBuildFeeBrightSickle() => byte(0xB3CC08)
function WeaponBuildFeeSoulSlicer() => byte(0xB3CC1C)
function WeaponBuildFeeSpiritScythe() => byte(0xB3CC30)
function WeaponBuildFeeShadowSickle() => byte(0xB3CC44)
function WeaponBuildFeeRageSlicer() => byte(0xB3CC58)
function WeaponBuildFeeChaosSickle() => byte(0xB3CC6C)
function WeaponBuildFeeAltenaScythe() => byte(0xB3CC80)
function WeaponBuildFeePhotonSaber() => byte(0xB3CC94)
function WeaponBuildPoeFairyPistol() => byte(0xB3CCA8)
function WeaponBuildPoeParallelmite() => byte(0xB3CCBC)
function WeaponBuildPoePoeSAutomatic() => byte(0xB3CCD0)
function WeaponBuildPoePoeCannon() => byte(0xB3CCE4)
function WeaponBuildPoePiptoeRifle() => byte(0xB3CCF8)
function WeaponBuildPoeParallelmite2() => byte(0xB3CD0C)
function WeaponBuildPoePistolMark3() => byte(0xB3CD20)
function WeaponBuildPoeGatlingGun() => byte(0xB3CD34)
function WeaponBuildPoeFairyPukoref() => byte(0xB3CD48)
function WeaponBuildPoePoeBlaster7() => byte(0xB3CD5C)
function WeaponBuildPoeSurgeCannon() => byte(0xB3CD70)
function WeaponBuildPoePoeMagnumSp() => byte(0xB3CD84)



function InGame() => byte(0x0031da24)

CurrentMapLocationRP = {
    0x0: "Eden Temple",
    0x2: "Alchemic City Noir",
    0x3: "Marmel Forest",
    0x4: "Belkhyde Gate",
    0x5: "Great Cave",
    0x6: "Scarlet Temple",
    0x7: "Aquitto Spring",
    0x8: "Weathervane Cave",
    0x9: "Crystal Monument",
    0xa: "Moon Tower",
    0xb: "Desert",
    0xc: "Oasis",
    0xd: "Tatalia Village",
    0xe: "Desert Fork",
    0xf: "Desert Ruins",
    0x10: "Great Desert",
    0x11: "West Regenbogen",
    0x12: "Weast Coast Highway",
    0x13: "Northen Cave",
    0x14: "Agito Cove",
    0x15: "Holy Path",
    0x16: "East Coast Highway",
    0x17: "Max's Camp",
    0x18: "Onuki Cave",
    0x19: "West Sessler Plains",
    0x1a: "Sessler Plains",
    0x1b: "Altena Forest",
    0x1c: "Altena Church",
    0x1d: "The Wetlands",
    0x1e: "Parnaky Cave",
    0x1f: "Forest of Ocean Mist",
    0x20: "North Grand Plains",
    0x21: "Grand City",
    0x22: "Mist Canyon",
    0x23: "Claire Village",
    0x24: "Lailzatt Cave",
    0x25: "Spring of Nelvia",
    0x26: "Mysterious Palace",
    0x27: "Dragon's Nest",
    0x28: "Grand Highway",
    0x29: "Imperial Camp",
    0x2a: "Alha Village",
    0x2b: "South Lake Midgard",
    0x2c: "Fort Zeyoung",
    0x2d: "East Regenbogen",
    0x2e: "South Grand Plains",
    0x2f: "Mt. Gelad",
    0x30: "South Grand Plains",
    0x31: "Dark Island",
    0x32: "Vintavne",
    0x33: "Sealed Ruin",
    0x34: "Back Alley",
    0x35: "Central Park",
    0x36: "Riese Palace",
    0x37: "Great Lighthouse",
    0x38: "Sewer",
    0x39: "Market",
    0x3a: "Dark Forest",
    0x3b: "Hidden Village",
    0x3c: "Dark Forest 2",
    0x3d: "Dark Spring",
    0x3e: "Dark Forest 3",
    0x3f: "Zwital Village",
    0x40: "Graveyard",
    0x41: "Tent",
}
EventFlagEpisode2LeaveTentAndNoinJoinsTheParty()
CurrentMainCharacterRP = {
    0x0: "Felt",
    0x1: "Viese",
}
CurrentGameStageRP = {
    0x0: "Prologue",
    0x1: "Ep. 1 - Beginning in Eden",
    0x2: "Ep. 2 - Belkhyde, the Other World",
    0x3: "Ep. 3 - The Share Ring",
    0x4: "Ep. 4 - Infiltrating Risevelt",
    0x5: "Ep. 5 - The Sea",
    0x6: "Ep. 6 - Assassin in White",
    0x7: "Ep. 7 - Gardo",
    0x8: "Ep. 8 - Rebirth of Fire",
    0x9: "Ep. 9 - Heroes of Confinement",
    0xa: "Ep. 10 - Into the Mist",
    0xb: "Ep. 11 - The Blood of an Alchemist",
    0xc: "Ep. 12 - Capital City Grande",
    0xd: "Ep. 13 - Imperial Camp Capture",
    0xe: "Ep. 14 - For he who has gone off to fight",
    0xf: "Ep. 15 - Beacon of Revolution",
    0x10: "Ep. 16 - Burden of Royalty",
    0x11: "Ep. 17 - Revival of Eden",
    0x12: "Ep. 18 - The Important Family",
    0x13: "Ep. 19 - The Last Battle",
    0x14: "Ep. 20 - Retracing Your Footsteps",
    0x15: "Ep. 21 - The Sealed One",
    0x16: "Ep. 22 - To the New World",
    0x17: "",
    0x18: "",
    0x19: "",
    0xff: "Prologue",
}
function PlaytimeSECS()
{
    return CurrentPlayTime() / 60
}
rich_presence_conditional_display(
    InGame() == 0x1 && OverworldIndicator() == 0x0 && EventFlagEpisode1VieseMetUpWithFeltAtBelkhydeGate() == 0x0 && EventFlagEpisode2LeaveTentAndNoinJoinsTheParty() == 0x0,
    "{0} | Playing as {1} | Location:{2} | Playtime:{3} | Levels - Viese:{4}",
    rich_presence_lookup("GameStage", PrimaryLoadSlotCurrentEpisode(), CurrentGameStageRP),
    rich_presence_lookup("CurrentCharacter", CurrentMainCharacter(), CurrentMainCharacterRP),
    rich_presence_lookup("CurrentMap", CurrentLocation(), CurrentMapLocationRP),
    rich_presence_value("PlayTime", PlaytimeSECS(), format="SECS"),
    rich_presence_value("VieseLevel", CharacterCurrentLevelViese(), format="VALUE")
)
rich_presence_conditional_display(
    InGame() == 0x1 && OverworldIndicator() == 0x1 && EventFlagEpisode1VieseMetUpWithFeltAtBelkhydeGate() == 0x0 && EventFlagEpisode2LeaveTentAndNoinJoinsTheParty() == 0x0,
    "{0} | Playing as {1} | Selecting Location | Playtime:{2} | Levels - Viese:{3}",
    rich_presence_lookup("GameStage", PrimaryLoadSlotCurrentEpisode(), CurrentGameStageRP),
    rich_presence_lookup("CurrentCharacter", CurrentMainCharacter(), CurrentMainCharacterRP),
    rich_presence_value("PlayTime", PlaytimeSECS(), format="SECS"),
    rich_presence_value("VieseLevel", CharacterCurrentLevelViese(), format="VALUE")
)
rich_presence_conditional_display(
    InGame() == 0x1 && OverworldIndicator() == 0x0 && EventFlagEpisode1VieseMetUpWithFeltAtBelkhydeGate() == 0x1 && EventFlagEpisode2LeaveTentAndNoinJoinsTheParty() == 0x0,
    "{0} | Playing as {1} | Location:{2} | Playtime:{3} | Levels - Viese:{4} • Felt:{5}",
    rich_presence_lookup("GameStage", PrimaryLoadSlotCurrentEpisode(), CurrentGameStageRP),
    rich_presence_lookup("CurrentCharacter", CurrentMainCharacter(), CurrentMainCharacterRP),
    rich_presence_lookup("CurrentMap", CurrentLocation(), CurrentMapLocationRP),
    rich_presence_value("PlayTime", PlaytimeSECS(), format="SECS"),
    rich_presence_value("VieseLevel", CharacterCurrentLevelViese(), format="VALUE"),
    rich_presence_value("FeltLevel", CharacterCurrentLevelFelt(), format="VALUE")
)
rich_presence_conditional_display(
    InGame() == 0x1 && OverworldIndicator() == 0x1 && EventFlagEpisode1VieseMetUpWithFeltAtBelkhydeGate() == 0x1 && EventFlagEpisode2LeaveTentAndNoinJoinsTheParty() == 0x0,
    "{0} | Playing as {1} | Selecting Location | Playtime:{2} | Levels - Viese:{3} • Felt:{4}",
    rich_presence_lookup("GameStage", PrimaryLoadSlotCurrentEpisode(), CurrentGameStageRP),
    rich_presence_lookup("CurrentCharacter", CurrentMainCharacter(), CurrentMainCharacterRP),
    rich_presence_value("PlayTime", PlaytimeSECS(), format="SECS"),
    rich_presence_value("VieseLevel", CharacterCurrentLevelViese(), format="VALUE"),
    rich_presence_value("FeltLevel", CharacterCurrentLevelFelt(), format="VALUE")
)
rich_presence_conditional_display(
    InGame() == 0x1 && OverworldIndicator() == 0x0 && EventFlagEpisode1VieseMetUpWithFeltAtBelkhydeGate() == 0x1 && EventFlagEpisode2LeaveTentAndNoinJoinsTheParty() == 0x1,
    "{0} | Playing as {1} | Location:{2} | Playtime:{3} | Levels - Viese:{4} • Felt:{5} • Noin:{6}",
    rich_presence_lookup("GameStage", PrimaryLoadSlotCurrentEpisode(), CurrentGameStageRP),
    rich_presence_lookup("CurrentCharacter", CurrentMainCharacter(), CurrentMainCharacterRP),
    rich_presence_lookup("CurrentMap", CurrentLocation(), CurrentMapLocationRP),
    rich_presence_value("PlayTime", PlaytimeSECS(), format="SECS"),
    rich_presence_value("VieseLevel", CharacterCurrentLevelViese(), format="VALUE"),
    rich_presence_value("FeltLevel", CharacterCurrentLevelFelt(), format="VALUE"),
    rich_presence_value("NoinLevel", CharacterCurrentLevelNoin(), format="VALUE")
)
rich_presence_conditional_display(
    InGame() == 0x1 && OverworldIndicator() == 0x1 && EventFlagEpisode1VieseMetUpWithFeltAtBelkhydeGate() == 0x1 && EventFlagEpisode2LeaveTentAndNoinJoinsTheParty() == 0x1,
    "{0} | Playing as {1} | Selecting Location | Playtime:{2} | Levels - Viese:{3} • Felt:{4} • Noin:{5}",
    rich_presence_lookup("GameStage", PrimaryLoadSlotCurrentEpisode(), CurrentGameStageRP),
    rich_presence_lookup("CurrentCharacter", CurrentMainCharacter(), CurrentMainCharacterRP),
    rich_presence_value("PlayTime", PlaytimeSECS(), format="SECS"),
    rich_presence_value("VieseLevel", CharacterCurrentLevelViese(), format="VALUE"),
    rich_presence_value("FeltLevel", CharacterCurrentLevelFelt(), format="VALUE"),
    rich_presence_value("NoinLevel", CharacterCurrentLevelNoin(), format="VALUE")
)
rich_presence_conditional_display(
    InGame() == 0x1 && OverworldIndicator() == 0x0,
    "{0} | Playing as {1} | Location:{2} | Playtime:{3} | Levels - Viese:{4} • Felt:{5} • Fee:{6} • Noin:{7} • Poe:{8} • Gray:{9}",
    rich_presence_lookup("GameStage", PrimaryLoadSlotCurrentEpisode(), CurrentGameStageRP),
    rich_presence_lookup("CurrentCharacter", CurrentMainCharacter(), CurrentMainCharacterRP),
    rich_presence_lookup("CurrentMap", CurrentLocation(), CurrentMapLocationRP),
    rich_presence_value("PlayTime", PlaytimeSECS(), format="SECS"),
    rich_presence_value("VieseLevel", CharacterCurrentLevelViese(), format="VALUE"),
    rich_presence_value("FeltLevel", CharacterCurrentLevelFelt(), format="VALUE"),
    rich_presence_value("FeeLevel", CharacterCurrentLevelFee(), format="VALUE"),
    rich_presence_value("NoinLevel", CharacterCurrentLevelNoin(), format="VALUE"),
    rich_presence_value("PoeLevel", CharacterCurrentLevelPoe(), format="VALUE"),
    rich_presence_value("GrayLevel", CharacterCurrentLevelGray(), format="VALUE")
)
rich_presence_conditional_display(
    InGame() == 0x1 && OverworldIndicator() == 0x1,
    "{0} | Playing as {1} | Selecting Location | Playtime:{2} | Levels - Viese:{3} • Felt:{4} • Fee:{5} • Noin:{6} • Poe:{7} • Gray:{8}",
    rich_presence_lookup("GameStage", PrimaryLoadSlotCurrentEpisode(), CurrentGameStageRP),
    rich_presence_lookup("CurrentCharacter", CurrentMainCharacter(), CurrentMainCharacterRP),
    rich_presence_value("PlayTime", PlaytimeSECS(), format="SECS"),
    rich_presence_value("VieseLevel", CharacterCurrentLevelViese(), format="VALUE"),
    rich_presence_value("FeltLevel", CharacterCurrentLevelFelt(), format="VALUE"),
    rich_presence_value("FeeLevel", CharacterCurrentLevelFee(), format="VALUE"),
    rich_presence_value("NoinLevel", CharacterCurrentLevelNoin(), format="VALUE"),
    rich_presence_value("PoeLevel", CharacterCurrentLevelPoe(), format="VALUE"),
    rich_presence_value("GrayLevel", CharacterCurrentLevelGray(), format="VALUE")
)
rich_presence_display("Playing Atelier Iris 2: The Azoth of Destiny")



//////////////////// Achievements to Follow ///////////////////ss


function ReachedLevel(levelFunc, threshold)
{
    return 
    InGame() == 0x1 &&
    prev(levelFunc) < threshold &&
    levelFunc >= threshold
}
function ReachedLevel50(levelFunc, threshold)
{
    return 
    InGame() == 0x1 &&
    prev(levelFunc) < threshold &&
    levelFunc == threshold
}

achievement(
    title = "Felt the Bearer",
    description = "Reach Lv 5 with Felt.",
    points = 3,
    trigger = never(MemoryCardAccessor() == 0x144240) &&
    ReachedLevel(CharacterCurrentLevelFelt(), 5)
)

achievement(
    title = "Azure Knight Felt",
    description = "Reach Lv 25 with Felt.",
    points = 5,
    trigger = never(MemoryCardAccessor() == 0x144240) &&
    ReachedLevel(CharacterCurrentLevelFelt(), 25)
)

achievement(
    title = "Master of the Azoth",
    description = "Reach Lv 50 with Felt.",
    points = 10,
    trigger = never(MemoryCardAccessor() == 0x144240) &&
    ReachedLevel50(CharacterCurrentLevelFelt(), 50)
)

achievement(
    title = "Viese the Apprentice",
    description = "Reach Lv 5 with Viese.",
    points = 3,
    trigger = never(MemoryCardAccessor() == 0x144240) &&
    ReachedLevel(CharacterCurrentLevelViese(), 5)

)

achievement(
    title = "Heir of Eden",
    description = "Reach Lv 25 with Viese.",
    points = 5,
    trigger = never(MemoryCardAccessor() == 0x144240) &&
    ReachedLevel(CharacterCurrentLevelViese(), 25)
)

achievement(
    title = "Steward of Eden",
    description = "Reach Lv 50 with Viese.",
    points = 10,
    trigger = never(MemoryCardAccessor() == 0x144240) &&
    ReachedLevel50(CharacterCurrentLevelViese(), 50)
)

achievement(
    title = "Iron Shield Noin",
    description = "Reach Lv 25 with Noin.",
    points = 5,
    trigger = never(MemoryCardAccessor() == 0x144240) &&
    ReachedLevel(CharacterCurrentLevelNoin(), 25)
)

achievement(
    title = "Protector of Belkhyde",
    description = "Reach Lv 50 with Noin.",
    points = 10,
    trigger = never(MemoryCardAccessor() == 0x144240) &&
    ReachedLevel50(CharacterCurrentLevelNoin(), 50)
)
achievement(
    title = "Reaper of Life",
    description = "Reach Lv 25 with Fee.",
    points = 5,
    trigger = never(MemoryCardAccessor() == 0x144240) &&
    ReachedLevel(CharacterCurrentLevelFee(), 25)
)

achievement(
    title = "Serene Reaper",
    description = "Reach Lv 50 with Fee.",
    points = 10,
    trigger = never(MemoryCardAccessor() == 0x144240) &&
    ReachedLevel50(CharacterCurrentLevelFee(), 50)
)
achievement(
    title = "Inventor of Mana",
    description = "Reach Lv 25 with Poe.",
    points = 5,
    trigger = never(MemoryCardAccessor() == 0x144240) &&
    ReachedLevel(CharacterCurrentLevelPoe(), 25)
)

achievement(
    title = "Alchemic Gunsmith",
    description = "Reach Lv 50 with Poe.",
    points = 10,
    trigger = never(MemoryCardAccessor() == 0x144240) &&
    ReachedLevel50(CharacterCurrentLevelPoe(), 50)
)
achievement(
    title = "Crimson Edge",
    description = "Reach Lv 25 with Gray.",
    points = 5,
    trigger = never(MemoryCardAccessor() == 0x144240) &&
    ReachedLevel(CharacterCurrentLevelGray(), 25)
)

achievement(
    title = "Knight of Justice",
    description = "Reach Lv 50 with Gray.",
    points = 10,
    trigger = never(MemoryCardAccessor() == 0x144240) &&
    ReachedLevel50(CharacterCurrentLevelGray(), 50)
)

function FeltAzothForgedCount()
{
    return
        (CharacterWeaponFeltAzureAzoth() / 2) +
        (CharacterWeaponFeltFlamingAzoth() / 2) +
        (CharacterWeaponFeltLightningAzoth() / 2) +
        (CharacterWeaponFeltGaleAzoth() / 2) +
        (CharacterWeaponFeltAlloyAzoth() / 2) +
        (CharacterWeaponFeltDarkAzoth() / 2) +
        (CharacterWeaponFeltHolyAzoth() / 2) +
        (CharacterWeaponFeltDivineAzoth() / 2) +
        (CharacterWeaponFeltSpiritAzoth() / 2) +
        (CharacterWeaponFeltAegisAzoth() / 2) +
        (CharacterWeaponFeltRoyalAzoth() / 2) +
        (CharacterWeaponFeltDestiny() / 2)
}

achievement(
    title = "Artisan of Azoth",
    description = "Forge half of Felt’s available Azoth blades.",
    points = 5,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(FeltAzothForgedCount()) < 6 &&
        FeltAzothForgedCount() >= 6
)

achievement(
    title = "True Wielder of Azoth",
    description = "Forge all of Felt’s Azoth blades.",
    points = 10,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(FeltAzothForgedCount()) < 12 &&
        measured(FeltAzothForgedCount() == 12)
)

function VieseStavesForgedCount()
{
    return
        (CharacterWeaponVieseAngelStaff() / 2) +
        (CharacterWeaponVieseFairyStaff() / 2) +
        (CharacterWeaponViesePrimStaff() / 2) +
        (CharacterWeaponVieseSorcererSStaff() / 2) +
        (CharacterWeaponVieseBashingQueen() / 2) +
        (CharacterWeaponVieseMuteStaff() / 2) +
        (CharacterWeaponVieseEbonyStaff() / 2) +
        (CharacterWeaponVieseSaintStaff() / 2) +
        (CharacterWeaponVieseProvidenceStaff() / 2) +
        (CharacterWeaponVieseHeavenlyStaff() / 2) +
        (CharacterWeaponVieseEarthlyStaff() / 2) +
        (CharacterWeaponVieseGoddessStaff() / 2)
}

achievement(
    title = "Arcane Creator",
    description = "Forge half of Viese’s staves.",
    points = 5,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(VieseStavesForgedCount()) < 6 &&
        VieseStavesForgedCount() >= 6
)

achievement(
    title = "Grand Alchemist’s Staff",
    description = "Forge all of Viese’s staves.",
    points = 10,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(VieseStavesForgedCount()) < 12 &&
        measured(VieseStavesForgedCount() == 12)
)

function NoinGauntletsForgedCount()
{
    return
        (CharacterWeaponNoinEizenKnuckle() / 2) +
        (CharacterWeaponNoinGauntlet() / 2) +
        (CharacterWeaponNoinCrystalClaw() / 2) +
        (CharacterWeaponNoinLehernKnuckle() / 2) +
        (CharacterWeaponNoinPointGetter() / 2) +
        (CharacterWeaponNoinSilverGauntlet() / 2) +
        (CharacterWeaponNoinMeteorGauntlet() / 2) +
        (CharacterWeaponNoinManaGlove() / 2) +
        (CharacterWeaponNoinMajinGauntlet() / 2) +
        (CharacterWeaponNoinHolyBandages() / 2) +
        (CharacterWeaponNoinGodspeedFist() / 2) +
        (CharacterWeaponNoinHolyBattleFist() / 2)
}

achievement(
    title = "Guardian’s Strength",
    description = "Forge half of Noin’s gauntlets.",
    points = 5,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(NoinGauntletsForgedCount()) < 6 &&
        NoinGauntletsForgedCount() >= 6
)

achievement(
    title = "Iron Vanguard",
    description = "Forge all of Noin’s gauntlets.",
    points = 10,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(NoinGauntletsForgedCount()) < 12 &&
        measured(NoinGauntletsForgedCount() == 12)
)

function FeeScythesForgedCount()
{
    return
        (CharacterWeaponFeeAssassinScythe() / 2) +
        (CharacterWeaponFeeCrossSlicer() / 2) +
        (CharacterWeaponFeeNightinggale() / 2) +
        (CharacterWeaponFeeBrightSickle() / 2) +
        (CharacterWeaponFeeSoulSlicer() / 2) +
        (CharacterWeaponFeeSpiritScythe() / 2) +
        (CharacterWeaponFeeShadowSickle() / 2) +
        (CharacterWeaponFeeRageSlicer() / 2) +
        (CharacterWeaponFeeChaosSickle() / 2) +
        (CharacterWeaponFeeAltenaScythe() / 2) +
        (CharacterWeaponFeePhotonSaber() / 2)
}

achievement(
    title = "Mist Dancer",
    description = "Forge half of Fee’s scythes.",
    points = 5,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(FeeScythesForgedCount()) < 5 &&
        FeeScythesForgedCount() >= 5
)

achievement(
    title = "Warden of Souls",
    description = "Forge all of Fee’s scythes.",
    points = 10,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(FeeScythesForgedCount()) < 11 &&
        measured(FeeScythesForgedCount() == 11)
)

function PoeGunsForgedCount()
{
    return
        (CharacterWeaponPoeFairyPistol() / 2) +
        (CharacterWeaponPoeParallelmite() / 2) +
        (CharacterWeaponPoePoeSAutomatic() / 2) +
        (CharacterWeaponPoePoeCannon() / 2) +
        (CharacterWeaponPoePipoteRifle() / 2) +
        (CharacterWeaponPoeParallelmite2() / 2) +
        (CharacterWeaponPoePistolMark3() / 2) +
        (CharacterWeaponPoeGatlingGun() / 2) +
        (CharacterWeaponPoeFairyPukoref() / 2) +
        (CharacterWeaponPoePoeBlaster7() / 2) +
        (CharacterWeaponPoeSurgeCannon() / 2) +
        (CharacterWeaponPoePoeMagnumSp() / 2)
}

achievement(
    title = "Machina Specialist",
    description = "Forge half of Poe’s guns.",
    points = 5,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(PoeGunsForgedCount()) < 6 &&
        PoeGunsForgedCount() >= 6
)

achievement(
    title = "Genius Engineer",
    description = "Forge all of Poe’s guns.",
    points = 10,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(PoeGunsForgedCount()) < 12 &&
        measured(PoeGunsForgedCount() == 12)
)


function GrayBladesForgedCount()
{
    return
        (CharacterWeaponGrayDragonKiller() / 2) +
        (CharacterWeaponGrayEnduranceBlade() / 2) +
        (CharacterWeaponGrayIceBlade() / 2) +
        (CharacterWeaponGrayThunderBlade() / 2) +
        (CharacterWeaponGrayVacuumBlade() / 2) +
        (CharacterWeaponGrayCrystalBlade() / 2) +
        (CharacterWeaponGrayPassionBlade() / 2) +
        (CharacterWeaponGrayRoadringBlade() / 2) +
        (CharacterWeaponGrayInvincibleBlade() / 2) +
        (CharacterWeaponGrayWarriorBlade() / 2) +
        (CharacterWeaponGrayRagingGod() / 2)
}

achievement(
    title = "Knight’s Pride",
    description = "Forge half of Gray’s blades.",
    points = 5,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(GrayBladesForgedCount()) < 5 &&
        GrayBladesForgedCount() >= 5
)

achievement(
    title = "Champion of Belkhyde",
    description = "Forge all of Gray’s blades.",
    points = 10,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(GrayBladesForgedCount()) < 11 &&
        measured(GrayBladesForgedCount() == 11)
)

function FeltSkillMasteryCount()
{
    return
        (SkillManaStrikeFelt() / 0x1) +
        (SkillAuraStrikeFelt() / 0xFA) +
        (SkillRagingStrikeFelt() / 0x1F4) +
        (SkillManaWaveFelt() / 0x1) +
        (SkillAuraWaveFelt() / 0x190) +
        (SkillRagingWaveFelt() / 0x2BC) +
        (SkillStrikeEdgeFelt() / 0x12C) +
        (SkillPhantomEdgeFelt() / 0x258) +
        (SkillFinalEdgeFelt() / 0x3E7) +
        (SkillBlueEnergyFelt() / 0x3E7) +
        (SkillManaWeaponFelt() / 0x12C) +
        (SkillManaShieldFelt() / 0x1F4) +
        (SkillLifeUpFelt() / 0x226) +
        (SkillOffenseFelt() / 0x190) +
        (SkillBlockFelt() / 0x12C) +
        (SkillMagicUpFelt() / 0x96) +
        (SkillDefenseUpFelt() / 0x15E) +
        (SkillDefenseFelt() / 0x12C) +
        (SkillAttackUpFelt() / 0x1C2) +
        (SkillExperienceUpFelt() / 0x356) +
        (SkillSpUpFelt() / 0x2EE) +
        (SkillExtraBlowFelt() / 0x3E7) +
        (SkillChargeUpFelt() / 0x190) +
        (SkillResistUpFelt() / 0xFA) +
        (SkillDoubleAttackFelt() / 0x2BC) +
        (SkillSpeedUpFelt() / 0x28A) +
        (SkillGutsFelt() / 0x1F4) +
        (SkillKnockbackFelt() / 0x190)
}

achievement(
    title = "Azure Artisan",
    description = "Master half of Felt’s skills.",
    points = 5,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(FeltSkillMasteryCount()) < 14 &&
        measured(FeltSkillMasteryCount() >= 14)
)

achievement(
    title = "Wielder of Creation",
    description = "Master all of Felt’s skills.",
    points = 10,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(FeltSkillMasteryCount()) < 28 &&
        measured(FeltSkillMasteryCount() == 28)
)

function VieseSkillMasteryCount()
{
    return
        (SkillCopperHandHealingViese() / 0x1) +
        (SkillSilverHandHealingViese() / 0x12C) +
        (SkillGoldHandHealingViese() / 0x384) +
        (SkillBlessOfRainViese() / 0x96) +
        (SkillHealingDropViese() / 0x12C) +
        (SkillHealingRainViese() / 0x258) +
        (SkillElementalExtractionViese() / 0x1) +
        (SkillWideExtractionViese() / 0xFA) +
        (SkillMegaExtractionViese() / 0x1F4) +
        (SkillWideItemViese() / 0x1) +
        (SkillPowerItemViese() / 0x1F4) +
        (SkillLivingItemViese() / 0x12C) +
        (SkillOffenseViese() / 0xFA) +
        (SkillDefenseViese() / 0xFA) +
        (SkillExperienceUpViese() / 0x96) +
        (SkillSpUpViese() / 0xFA) +
        (SkillDodgeViese() / 0x12c) +
        (SkillAttackUpViese() / 0x15E) +
        (SkillMagicGuardViese() / 0x190) +
        (SkillMagicUpViese() / 0x190) +
        (SkillSpeedUpViese() / 0x226) +
        (SkillResistUpViese() / 0x1C2) +
        (SkillHealViese() / 0x258) +
        (SkillMagicUpViese() / 0x352) +
        (SkillDefenseUpViese() / 0x28A) +
        (SkillRestoreViese() / 0x3E7) +
        (SkillLifeUpViese() / 0x2EE) +
        (SkillGutsViese() / 0x320)
}

achievement(
    title = "Eden’s Scholar",
    description = "Master half of Viese’s skills.",
    points = 5,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(VieseSkillMasteryCount()) < 14 &&
        VieseSkillMasteryCount() >= 14
)

achievement(
    title = "Voice of Mana",
    description = "Master all of Viese’s skills.",
    points = 10,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(VieseSkillMasteryCount()) < 28 &&
        measured(VieseSkillMasteryCount() == 28)
)


function NoinSkillMasteryCount()
{
    return
        (SkillForceBlastNoin() / 0x1) +
        (SkillStormBlastNoin() / 0x12C) +
        (SkillFalconBlastNoin() / 0x226) +
        (SkillComboAttackNoin() / 0xC8) +
        (SkillFuryComboNoin() / 0x1F4) +
        (SkillNoinComboNoin() / 0x3E7) +
        (SkillHealBreezeNoin() / 0x1) +
        (SkillHealWindNoin() / 0xFA) +
        (SkillGaleHealNoin() / 0x1F4) +
        (SkillSuckerKickNoin() / 0x12C) +
        (SkillHealingLightNoin() / 0x12C) +
        (SkillAdrenalineNoin() / 0x3E7) +
        (SkillLifeUpNoin() / 0x1C2) +
        (SkillDefenseUpNoin() / 0x226) +
        (SkillDefenseNoin() / 0x12C) +
        (SkillEsperienceUpNoin() / 0x2EE) +
        (SkillAttackUpNoin() / 0x15E) +
        (SkillMagicUpNoin() / 0xFA) +
        (SkillOffenseNoin() / 0x15E) +
        (SkillSpUpNoin() / 0x352) +
        (SkillDouleAttackNoin() / 0x1F4) +
        (SkillDodgeNoin() / 0xFA) +
        (SkillResistUpNoin() / 0x96) +
        (SkillSpeedUpNoin() / 0x28A) +
        (SkillGutsNoin() / 0x2BC) +
        (SkillQuickNoin() / 0x3E7) +
        (SkillKnockbackNoin() / 0x190) +
        (SkillCounterNoin() / 0x1F4)
}

achievement(
    title = "Guardian’s Resolve",
    description = "Master half of Noin’s skills.",
    points = 5,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(NoinSkillMasteryCount()) < 14 &&
        NoinSkillMasteryCount() >= 14
)

achievement(
    title = "Unbreakable Bulwark",
    description = "Master all of Noin’s skills.",
    points = 10,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(NoinSkillMasteryCount()) < 28 &&
        measured(NoinSkillMasteryCount() == 28)
)

function FeeSkillMasteryCount()
{
    return
        (SkillAirSlicerFee() / 0x1) +
        (SkillTwinSlicerFee() / 0xFA) +
        (SkillEndlessBladeFee() / 0x1F4) +
        (SkillEinZecksclawFee() / 0x1) +
        (SkillEinZeckslashFee() / 0x1F4) +
        (SkillEinZecksdanceFee() / 0x3E7) +
        (SkillDivineDrainFee() / 0x1F4) +
        (SkillDivineSealFee() / 0x1F4) +
        (SkillDivineStunFee() / 0x1) +
        (SkillShadowEndFee() / 0x3E7) +
        (SkillAvatarFee() / 0x3E7) +
        (SkillZaleShineFee() / 0x258) +
        (SkillAttackUpFee() / 0x96) +
        (SkillDefenseUpFee() / 0xFA) +
        (SkillMagicUp1Fee() / 0x190) +
        (SkillExperienceUpFee() / 0x2EE) +
        (SkillMagicUpFee() / 0x28A) +
        (SkillOffenseFee() / 0x12C) +
        (SkillLifeUpFee() / 0x15E) +
        (SkillDefenseFee() / 0x190) +
        (SkillSpUpFee() / 0x352) +
        (SkillDodgeFee() / 0xFA) +
        (SkillDoubleAttackFee() / 0x258) +
        (SkillSpeedUpFee() / 0x1C2) +
        (SkillResistUpFee() / 0x226) +
        (SkillGutsFee() / 0x258) +
        (SkillQuickFee() / 0x3E7) +
        (SkillCounterFee() / 0x1C2)
}

achievement(
    title = "Silent Elegy",
    description = "Master half of Fee’s skills.",
    points = 5,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(FeeSkillMasteryCount()) < 14 &&
        FeeSkillMasteryCount() >= 14
)

achievement(
    title = "Scythe of Serenity",
    description = "Master all of Fee’s skills.",
    points = 10,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(FeeSkillMasteryCount()) < 28 &&
        measured(FeeSkillMasteryCount() == 28)
)

function PoeSkillMasteryCount()
{
    return
        (SkillFunnyBulletPoe() / 0x1) +
        (SkillMysteryBulletPoe() / 0x96) +
        (SkillBulletSurpisePoe() / 0x12C) +
        (SkillPoeFirecrackerPoe() / 0xC8) +
        (SkillPoeDynamitePoe() / 0x190) +
        (SkillPoeDynamiteExPoe() / 0x258) +
        (SkillPoeMissilePoe() / 0x1) +
        (SkillPoeMissileMk2Poe() / 0xFA) +
        (SkillPoeMissileMk3Poe() / 0x1f4) +
        (SkillRefuelShotPoe() / 0x1) +
        (SkillPoeBazookaPoe() / 0x3E7) +
        (SkillSlowBulletPoe() / 0x1F4) +
        (SkillOffensePoe() / 0x12C) +
        (SkillBlockPoe() / 0x15E) +
        (SkillAttackUpPoe() / 0x1F4) +
        (SkillDefenseUpPoe() / 0x1F4) +
        (SkillDefensePoe() / 0x15E) +
        (SkillLifeUpPoe() / 0x1F4) +
        (SkillExperienceUpPoe() / 0x1F4) +
        (SkillSpUpPoe() / 0x1F4) +
        (SkillMagicUpPoe() / 0x1F4) +
        (SkillChargeUpPoe() / 0x12C) +
        (SkillFeintShotPoe() / 0x3E7) +
        (SkillRegenPoe() / 0x258) +
        (SkillResistUpPoe() / 0x1F4) +
        (SkillDoubleAttackPoe() / 0x190) +
        (SkillSpeedUpPoe() / 0x1F4) +
        (SkillGutsPoe() / 0x2BC)
}

achievement(
    title = "Tinker’s Insight",
    description = "Master half of Poe’s skills.",
    points = 5,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(PoeSkillMasteryCount()) < 14 &&
        PoeSkillMasteryCount() >= 14
)

achievement(
    title = "Machina Virtuoso",
    description = "Master all of Poe’s skills.",
    points = 10,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(PoeSkillMasteryCount()) < 28 &&
        measured(PoeSkillMasteryCount() == 28)
)

function GraySkillMasteryCount()
{
    return
        (SkillTwinDragonGray() / 0x1) +
        (SkillShreddingDragonGray() / 0x1F4) +
        (SkillDragonRuinGray() / 0x3E7) +
        (SkillHolyBladeGray() / 0x1) +
        (SkillFlamingBladeGray() / 0x12C) +
        (SkillInfernalBladeGray() / 0x258) +
        (SkillTeraFlameGray() / 0x2BC) +
        (SkillTauntGray() / 0x258) +
        (SkillDragonSCryGray() / 0x1) +
        (SkillFireBreathGray() / 0x1) +
        (SkillIceBreathGray() / 0x12C) +
        (SkillThunderBreathGray() / 0x12C) +
        (SkillOffenseGray() / 0x1F4) +
        (SkillDefenseUpGray() / 0x1C2) +
        (SkillBlockGray() / 0xFA) +
        (SkillLifeUpGray() / 0x28A) +
        (SkillExperienceUpGray() / 0x353) +
        (SkillAttackUpGray() / 0x226) +
        (SkillMagicUpGray() / 0xFA) +
        (SkillDragonSlayerGray() / 0x1) +
        (SkillDefenseGray() / 0x12C) +
        (SkillSpUpGray() / 0x2EE) +
        (SkillRegenGray() / 0x1F4) +
        (SkillChargeUpGray() / 0x15E) +
        (SkillResistUpGray() / 0x15E) +
        (SkillGutsGray() / 0x320) +
        (SkillSpeedUpGray() / 0x96) +
        (SkillKnockbackGray() / 0x12C)
}

achievement(
    title = "Blade of Resolve",
    description = "Master half of Gray’s skills.",
    points = 5,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(GraySkillMasteryCount()) < 14 &&
        GraySkillMasteryCount() >= 14
)

achievement(
    title = "Crimson Virtue",
    description = "Master all of Gray’s skills.",
    points = 10,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(GraySkillMasteryCount()) < 28 &&
        measured(GraySkillMasteryCount() == 28)
)


achievement(
    title = "Ember of Fire",
    description = "Max out the Fire element.",
    points = 5,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(FireElementQuantity()) < 0x63 &&
        FireElementQuantity() == 0x63
)

achievement(
    title = "Breath of Air",
    description = "Max out the Air element.",
    points = 5,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(AirElementQuantity()) < 0x63 &&
        AirElementQuantity() == 0x63
)

achievement(
    title = "Tide of Water",
    description = "Max out the Water element.",
    points = 5,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(WaterElementQuantity()) < 0x63 &&
        WaterElementQuantity() == 0x63
)

achievement(
    title = "Storm of Lightning",
    description = "Max out the Lightning element.",
    points = 5,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(LightningElementQuantity()) < 0x63 &&
        LightningElementQuantity() == 0x63
)

achievement(
    title = "Shadow of Dark",
    description = "Max out the Dark element.",
    points = 5,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(DarkElementQuantity()) < 0x63 &&
        DarkElementQuantity() == 0x63
)

achievement(
    title = "Heart of Stone",
    description = "Max out the Stone element.",
    points = 5,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(StoneElementQuantity()) < 0x63 &&
        StoneElementQuantity() == 0x63
)

achievement(
    title = "Roots of Wood",
    description = "Max out the Wood element.",
    points = 5,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(WoodElementQuantity()) < 0x63 &&
        WoodElementQuantity() == 0x63
)

achievement(
    title = "Light of Life",
    description = "Max out the Life element.",
    points = 5,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(LifeElementQuantity()) < 0x63 &&
        LifeElementQuantity() == 0x63
)

achievement(
    title = "Veil of Illusion",
    description = "Max out the Illusion element.",
    points = 5,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(IllusionElementQuantity()) < 0x63 &&
        IllusionElementQuantity() == 0x63
)

achievement(
    title = "Echo of Sound",
    description = "Max out the Sound element.",
    points = 5,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(SoundElementQuantity()) < 0x63 &&
        SoundElementQuantity() == 0x63
)

achievement(
    title = "Fragrance of Aroma",
    description = "Max out the Aroma element.",
    points = 5,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(AromaElementQuantity()) < 0x63 &&
        AromaElementQuantity() == 0x63
)

achievement(
    title = "Touch of Poison",
    description = "Max out the Poison element.",
    points = 5,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(PoisonElementQuantity()) < 0x63 &&
        PoisonElementQuantity() == 0x63
)

achievement(
    title = "Soul of Metal",
    description = "Max out the Metal element.",
    points = 5,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(MetalElementQuantity()) < 0x63 &&
        MetalElementQuantity() == 0x63
)

function ManaItemListProgress() {
    return ManaItemListFlagHealHerb() +
        ManaItemListFlagHealJar() +
        ManaItemListFlagFlame() +
        ManaItemListFlagMegaFlame() +
        ManaItemListFlagTerraFlame() +
        ManaItemListFlagCraft() +
        ManaItemListFlagBombIce() +
        ManaItemListFlagLightningRod() +
        ManaItemListFlagThunderRod() +
        ManaItemListFlagHealBulb() +
        ManaItemListFlagCureJar() +
        ManaItemListFlagMeteor() +
        ManaItemListFlagAmanitaNeedle() +
        ManaItemListFlagBasiliskEye() +
        ManaItemListFlagDragonGem() +
        ManaItemListFlagIceComet() +
        ManaItemListFlagFluteOfCerberus() +
        ManaItemListFlagDarkLightningRod() +
        ManaItemListFlagGlobe() +
        ManaItemListFlagAstralGlobe() +
        ManaItemListFlagUnderGlobe() +
        ManaItemListFlagNectar() +
        ManaItemListFlagAltenaJar() +
        ManaItemListFlagRefuel() +
        ManaItemListFlagHuffinWater() +
        ManaItemListFlagDiselement() +
        ManaItemListFlagCureCrystal() +
        ManaItemListFlagAromaPot() +
        ManaItemListFlagFearBottle() +
        ManaItemListFlagPendulum() +
        ManaItemListFlagReturnGem() +
        ManaItemListFlagPhilosophicAsh() +
        ManaItemListFlagUroborusPill() +
        ManaItemListFlagItemWish() +
        ManaItemListFlagElixir() +
        ManaItemListFlagDivineShield() +
        ManaItemListFlagPowerShield() +
        ManaItemListFlagDarkWater() +
        ManaItemListFlagElementBlaze() +
        ManaItemListFlagTimeStone() +
        ManaItemListFlagUni() +
        ManaItemListFlagSuperUni() +
        ManaItemListFlagUruCore() +
        ManaItemListFlagNymphCore() +
        ManaItemListFlagSilwestCore() +
        ManaItemListFlagPluaCore() +
        ManaItemListFlagZuvelkCore() +
        ManaItemListFlagFaustusCore() +
        ManaItemListFlagAionCore() +
        ManaItemListFlagWonderGrow() +
        ManaItemListFlagYugdoreWater() +
        ManaItemListFlagFairyTea() +
        ManaItemListFlagGrapplingHook() +
        ManaItemListFlagGlowLamp() +
        ManaItemListFlagFlayHammer() +
        ManaItemListFlagAnimalCookie() +
        ManaItemListFlagRainbowCloth() +
        ManaItemListFlagDestoneOrb() +
        ManaItemListFlagKeyOfHermes() +
        ManaItemListFlagMegidoSKey() +
        ManaItemListFlagMellOrb()
}


achievement(
    title = "Mana Collector",
    description = "Complete 50% of the Mana item list.",
    points = 5,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        ManaItemListProgress() >= 0x3d &&
        prev(ManaItemListProgress()) < 0x3d
)

achievement(
    title = "Mana Master",
    description = "Complete 100% of the Mana item list.",
    points = 10,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        measured(ManaItemListProgress() == 0x7a) &&
        prev(ManaItemListProgress() < 0x7a
    )
)

function AccessoryItemListProgress() {
    return AccessoryItemsFairyClothes() +
        AccessoryItemsFairyHat() +
        AccessoryItemsPigeonBlood() +
        AccessoryItemsAresLiquid() +
        AccessoryItemsSlaithCrown() +
        AccessoryItemsGradinCrown() +
        AccessoryItemsAncientMask() +
        AccessoryItemsTotemShield() +
        AccessoryItemsDragonShield() +
        AccessoryItemsSpiritProtect() +
        AccessoryItemsEdenOutfit() +
        AccessoryItemsRotenHelm() +
        AccessoryItemsBlauHelm() +
        AccessoryItemsSilverArmor() +
        AccessoryItemsPendelook() +
        AccessoryItemsDarkFairyClothes() +
        AccessoryItemsDarkFairyHat() +
        AccessoryItemsSlaithDress() +
        AccessoryItemsMagicPaper() +
        AccessoryItemsDemonRing() +
        AccessoryItemsDragonFangEarring() +
        AccessoryItemsLotaCake() +
        AccessoryItemsPlattin() +
        AccessoryItemsGurguSCane() +
        AccessoryItemsFireBrand() +
        AccessoryItemsIceBrand() +
        AccessoryItemsLightningBrand() +
        AccessoryItemsDazaSBelt() +
        AccessoryItemsGargoylesMirror() +
        AccessoryItemsAnkh() +
        AccessoryItemsMushroomArmor() +
        AccessoryItemsSoulShroud() +
        AccessoryItemsMagicPipe() +
        AccessoryItemsAromaTalisman() +
        AccessoryItemsNivTiara() +
        AccessoryItemsDiemaAnkh() +
        AccessoryItemsIllusionBracelet() +
        AccessoryItemsAngelFeather() +
        AccessoryItemsSpeedster() +
        AccessoryItemsAromaMaterial()
}


achievement(
    title = "Accessory Collector",
    description = "Complete 50% of the Accessory list.",
    points = 5,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        AccessoryItemListProgress() >= 0x28 &&
        prev(AccessoryItemListProgress()) < 0x28
)

achievement(
    title = "Accessory Master",
    description = "Complete 100% of the Accessory list.",
    points = 10,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        measured(AccessoryItemListProgress() == 0x50) &&
        prev(AccessoryItemListProgress() < 0x50
    )
)

function AlchemyItemListProgress() {
    return AlchemyItemsBlueBracer() +
        AlchemyItemsEliteLiqueur() +
        AlchemyItemsHolyEvergreen() +
        AlchemyItemsCharcoal() +
        AlchemyItemsBelkBlackbelt() +
        AlchemyItemsDamaskRing() +
        AlchemyItemsCottonCloth() +
        AlchemyItemsSilkCloth() +
        AlchemyItemsFormalFabric() +
        AlchemyItemsCometGem() +
        AlchemyItemsMagatamaCone() +
        AlchemyItemsRedCrystal() +
        AlchemyItemsWhiteCrystal() +
        AlchemyItemsMagneticCrystal() +
        AlchemyItemsAlchemistMedal() +
        AlchemyItemsSagesFeatherPen() +
        AlchemyItemsCrystaleavy() +
        AlchemyItemsCrystalite() +
        AlchemyItemsNauticalCharts() +
        AlchemyItemsCelestialMap() +
        AlchemyItemsDarkScroll() +
        AlchemyItemsMoonDrop() +
        AlchemyItemsNewMoonDrop() +
        AlchemyItemsFogBox() +
        AlchemyItemsSilverAcid() +
        AlchemyItemsManatini() +
        AlchemyItemsManaMoebius() +
        AlchemyItemsGravityCrystal() +
        AlchemyItemsBloodClay() +
        AlchemyItemsGrayCrowbar() +
        AlchemyItemsSilverCrowbar() +
        AlchemyItemsGoldCrowbar() +
        AlchemyItemsRotorAnkh() +
        AlchemyItemsQuicksilverAnkh() +
        AlchemyItemsSpitefulStone() +
        AlchemyItemsVieseCharm() +
        AlchemyItemsSunAndWindWing() +
        AlchemyItemsCueparts() +
        AlchemyItemsReptileEgg() +
        AlchemyItemsVerdureDoublet() +
        AlchemyItemsRubyPrism()
}


achievement(
    title = "Alchemy Researcher",
    description = "Complete 50% of the Alchemy item list.",
    points = 5,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        AlchemyItemListProgress() >= 0x29 &&
        prev(AlchemyItemListProgress()) < 0x29
)

achievement(
    title = "Alchemy Master",
    description = "Complete 100% of the Alchemy item list.",
    points = 10,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        measured(AlchemyItemListProgress() == 0x52) &&
        prev(AlchemyItemListProgress() < 0x52
    )
)

function HarvestedItemListProgress() {
    return HarvestedItemsMagiGrass() / 0x2 + HarvestedItemsOldMagiGrass() / 0x2 + HarvestedItemsYadokFungo() / 0x2 +
        HarvestedItemsOldYadokFungo() / 0x2 + HarvestedItemsAihieFungo() / 0x2 + HarvestedItemsNue() / 0x2 +
        HarvestedItemsSuperNue() / 0x2 + HarvestedItemsUrob() / 0x2 + HarvestedItemsTingleberry() / 0x2 +
        HarvestedItemsPearlberry() / 0x2 + HarvestedItemsTataliaCotton() / 0x2 + HarvestedItemsGlowgrass() / 0x2 +
        HarvestedItemsDryGlowgrass() / 0x2 + HarvestedItemsFreshGlowgrass() / 0x2 + HarvestedItemsTriffid() / 0x2 +
        HarvestedItemsHuffin() / 0x2 + HarvestedItemsPureWater() / 0x2 + HarvestedItemsFoulWater() / 0x2 +
        HarvestedItemsGoatMilk() / 0x2 + HarvestedItemsDoreWater() / 0x2 + HarvestedItemsGradenSalt() / 0x2 +
        HarvestedItemsFlour() / 0x2 + HarvestedItemsWax() / 0x2 + HarvestedItemsAle() / 0x2 +
        HarvestedItemsRedWine() / 0x2 + HarvestedItemsIndustrialAlcohol() / 0x2 + HarvestedItemsSilverWater() / 0x2 +
        HarvestedItemsDragonHorn() / 0x2 + HarvestedItemsDragonBlood() / 0x2 + HarvestedItemsRedLegien() / 0x2 +
        HarvestedItemsSilverLegien() / 0x2 + HarvestedItemsOre() / 0x2 + HarvestedItemsRedOre() / 0x2 +
        HarvestedItemsLargeRedOre() / 0x2 + HarvestedItemsDemOre() / 0x2 + HarvestedItemsAeronium() / 0x2 +
        HarvestedItemsLargeAeronium() / 0x2 + HarvestedItemsAncientCore() / 0x2 + HarvestedItemsIceStone() / 0x2 +
        HarvestedItemsDragonBone() / 0x2 + HarvestedItemsDragonMeat() / 0x2 + HarvestedItemsShadowStone() / 0x2 +
        HarvestedItemsCometStone() / 0x2 + HarvestedItemsGravityStone() / 0x2 + HarvestedItemsLightningStone() / 0x2 +
        HarvestedItemsDesertStone() / 0x2 + HarvestedItemsMoonStone() / 0x2 + HarvestedItemsWildMeat() / 0x2 +
        HarvestedItemsSpoiledMeat() / 0x2 + HarvestedItemsFrozenRain() / 0x2 + HarvestedItemsMiniPendelook() / 0x2 +
        HarvestedItemsDragonTongue() / 0x2 + HarvestedItemsPhoenixQuill() / 0x2 + HarvestedItemsPuniball() / 0x2 +
        HarvestedItemsFauxPuniball() / 0x2 + HarvestedItemsString() / 0x2 + HarvestedItemsHexiGlass() / 0x2 +
        HarvestedItemsPikohammer() / 0x2 + HarvestedItemsGroovecube() / 0x2 + HarvestedItemsGlobeball() / 0x2 +
        HarvestedItemsVioletFungus() / 0x2 + HarvestedItemsGogoSuit() / 0x2 + HarvestedItemsRainbowDisc() / 0x2 +
        HarvestedItemsStarPiece() / 0x2 + HarvestedItemsDarkMana() / 0x2 + HarvestedItemsBlackMana() / 0x2 +
        HarvestedItemsGlowingMana() / 0x2 + HarvestedItemsRedMana() / 0x2 + HarvestedItemsYellowMana() / 0x2 +
        HarvestedItemsGreenMana() / 0x2 + HarvestedItemsBlueMana() / 0x2
}



achievement(
    title = "Harvest Forager",
    description = "Complete 50% of the Harvested item list.",
    points = 5,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        HarvestedItemListProgress() >= 0x26 &&
        prev(HarvestedItemListProgress()) < 0x26
)

achievement(
    title = "Harvest Master",
    description = "Complete 100% of the Harvested item list.",
    points = 10,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        measured(HarvestedItemListProgress() == 0x47) &&
        prev(HarvestedItemListProgress() < 0x47)
)

function KeyItemListProgress() {
    return KeyItemsLibraryPass() / 0x2 + KeyItemsFireGem() / 0x2 + KeyItemsWindGem() / 0x2 + KeyItemsAquaGem() / 0x2 +
        KeyItemsLightGem() / 0x2 + KeyItemsDarkGem() / 0x2 + KeyItemsStoneGem() / 0x2 + KeyItemsWoodGem() / 0x2 +
        KeyItemsLifeGem() / 0x2 + KeyItemsDreamGem() / 0x2 + KeyItemsSoundGem() / 0x2 + KeyItemsFloraGem() / 0x2 +
        KeyItemsPoisonGem() / 0x2 + KeyItemsGoldenGem() / 0x2 + KeyItemsShareRing() / 0x2 +
        KeyItemsPetroglyphManual() / 0x2 + KeyItemsHalFlower() / 0x2 + KeyItemsVisa() / 0x2 +
        KeyItemsDowsingGuide() / 0x2 + KeyItemsTolenaSLetter() / 0x2 + KeyItemsYugenDiaryVol2() / 0x2 +
        KeyItemsMirrorOfTwilight() / 0x2 + KeyItemsLeginSWing() / 0x2 + KeyItemsElusmusFragment() / 0x2 +
        KeyItemsYO17jBlueprints() / 0x2 + KeyItemsWorkshopMap() / 0x2 + KeyItemsAlchemy101() / 0x2 +
        KeyItemsWeaponGuide() / 0x2 + KeyItemsGardenBook() / 0x2 + KeyItemsClothspinner() / 0x2 +
        KeyItemsTheLight() / 0x2 + KeyItemsAntidoteGuide() / 0x2 + KeyItemsTheLife() / 0x2 +
        KeyItemsAlchemicEcon() / 0x2 + KeyItemsReincarnationRecipe() / 0x2 + KeyItemsYachSNotes() / 0x2 +
        KeyItemsManners101() / 0x2 + KeyItemsMagicSnackRecipe() / 0x2 + KeyItemsAlchemicHistory() / 0x2 +
        KeyItemsSoulGenesis() / 0x2 + KeyItemsIrisNotes() / 0x2 + KeyItemsBookOfHermes() / 0x2 +
        KeyItemsBookAlha() / 0x2 + KeyItemsChaosDiary() / 0x2 + KeyItemsAncientSkills() / 0x2 +
        KeyItemsBookOfMarcus() / 0x2 + KeyItemsAlchemicDestiny() / 0x2 + KeyItemsBlacksmith101() / 0x2 +
        KeyItemsMythology1() / 0x2 + KeyItemsMythology2() / 0x2 + KeyItemsBookOfTroth() / 0x2 +
        KeyItemsHealingSkills() / 0x2 + KeyItemsMeMyselfBomb() / 0x2 + KeyItemsMyUltimateBomb() / 0x2 +
        KeyItemsLumliaTheKnight() / 0x2 + KeyItemsBotany101() / 0x2 + KeyItemsManaPower() / 0x2 +
        KeyItemsPirateBramus() / 0x2 + KeyItemsHeavenEarth() / 0x2 + KeyItemsHeavenlySigh() / 0x2 +
        KeyItemsManaPowerPower() / 0x2 + KeyItemsInstructionManual() / 0x2 + KeyItemsFallenBook() / 0x2 +
        KeyItemsTownHistory() / 0x2 + KeyItemsIceAge() / 0x2 + KeyItemsEllis() / 0x2 +
        KeyItemsIllusionalVacation() / 0x2 + KeyItemsMysticBeast() / 0x2 + KeyItemsBelkhyde() / 0x2 +
        KeyItemsMysticalBeast() / 0x2 + KeyItemsFairyTales() / 0x2 + KeyItemsNoName1() / 0x2 +
        KeyItemsNoName2() / 0x2 + KeyItemsBookOfUroborus() / 0x2 + KeyItemsSlaithSongs() / 0x2 +
        KeyItemsGeology() / 0x2 + KeyItemsBlacksmithAdvanced() / 0x2 + KeyItemsVeekTactics() / 0x2 +
        KeyItemsVieseSRecipe() / 0x2 + KeyItemsBbq101() / 0x2 + KeyItemsJewelOfEden() / 0x2 +
        KeyItemsChurchTale() / 0x2 + KeyItemsTikTik() / 0x2 + KeyItemsMiracleStone() / 0x2 +
        KeyItemsShiningMetal() / 0x2 + KeyItemsNoir() / 0x2 + KeyItemsCrystal101() / 0x2 +
        KeyItemsBookOfInfinia() / 0x2 + KeyItemsHolyScript() / 0x2 + KeyItemsPaperSkills() / 0x2 +
        KeyItemsManners101() / 0x2 + KeyItemsExperiment() / 0x2 + KeyItemsMellAndTheMonster() / 0x2 +
        KeyItemsRevival() / 0x2 + KeyItemsAmanitaSDiary() / 0x2 + KeyItemsCursedMan() / 0x2 +
        KeyItemsLiquidification() / 0x2 + KeyItemsSlaithHistory() / 0x2 + KeyItemsMysticBeast2() / 0x2 +
        KeyItemsDragonSlayerTales() / 0x2 + KeyItemsLeneal() / 0x2 + KeyItemsLostItem() / 0x2 +
        KeyItemsManaPowerWind() / 0x2 + KeyItemsManaPowerDark() / 0x2 + KeyItemsManaPowerEvil() / 0x2 +
        KeyItemsManaPowerLife() / 0x2 + KeyItemsMilitaryTactics() / 0x2 + KeyItemsTheNewElement() / 0x2 +
        KeyItemsSlaithFashion() / 0x2 + KeyItemsNekoSWork() / 0x2 + KeyItemsStorm() / 0x2 +
        KeyItemsNeokSWork2() / 0x2 + KeyItemsIntellect() / 0x2 + KeyItemsHopesAndDreams() / 0x2 +
        KeyItemsFairyLife1() / 0x2 + KeyItemsFairyLife2() / 0x2 + KeyItemsSoulBook() / 0x2 +
        KeyItemsTheBookOfSoil() / 0x2 + KeyItemsWeatherReport() / 0x2
}


achievement(
    title = "Key Item Finder",
    description = "Complete 50% of the Key Item list.",
    points = 5,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        KeyItemListProgress() >= 0x3c &&
        prev(KeyItemListProgress()) < 0x3c
)

achievement(
    title = "Key Item Archivist",
    description = "Complete 100% of the Key Item list.",
    points = 10,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        measured(KeyItemListProgress() == 0x77) &&
        prev(KeyItemListProgress() < 0x77
    )
)


function MonsterListProgress() {
    return 
    bit2(0xB2A634) + bit3(0xB2A634) + bit4(0xB2A634) + bit5(0xB2A634) + bit6(0xB2A634) +
    bit2(0xB2A635) + bit3(0xB2A635) + bit4(0xB2A635) + bit5(0xB2A635) + bit6(0xB2A635) +
    bit2(0xB2A636) + bit3(0xB2A636) + bit4(0xB2A636) + bit6(0xB2A636) +
    bit2(0xB2A637) + bit3(0xB2A637) + bit4(0xB2A637) + bit6(0xB2A637) +
    bit2(0xB2A638) + bit3(0xB2A638) + bit4(0xB2A638) + bit6(0xB2A638) +
    bit2(0xB2A639) + bit3(0xB2A639) + bit4(0xB2A639) + bit5(0xB2A639) + bit6(0xB2A639) +
    bit2(0xB2A63A) + bit3(0xB2A63A) + bit4(0xB2A63A) + bit5(0xB2A63A) + bit6(0xB2A63A) +
    bit2(0xB2A63B) + bit3(0xB2A63B) + bit4(0xB2A63B) + bit5(0xB2A63B) + bit6(0xB2A63B) +
    bit2(0xB2A63C) + bit3(0xB2A63C) + bit4(0xB2A63C) + bit5(0xB2A63C) + bit6(0xB2A63C) +
    bit2(0xB2A63D) + bit3(0xB2A63D) + bit4(0xB2A63D) + bit5(0xB2A63D) + bit6(0xB2A63D) +
    bit2(0xB2A63E) + bit3(0xB2A63E) + bit4(0xB2A63E) + bit5(0xB2A63E) + bit6(0xB2A63E) +
    bit2(0xB2A63F) + bit3(0xB2A63F) + bit4(0xB2A63F) + bit5(0xB2A63F) + bit6(0xB2A63F) +
    bit2(0xB2A640) + bit3(0xB2A640) + bit4(0xB2A640) + bit5(0xB2A640) + bit6(0xB2A640) +
    bit2(0xB2A641) + bit3(0xB2A641) + bit4(0xB2A641) + bit5(0xB2A641) + bit6(0xB2A641) +
    bit2(0xB2A642) + bit3(0xB2A642) + bit4(0xB2A642) + bit5(0xB2A642) + bit6(0xB2A642) +
    bit2(0xB2A643) + bit3(0xB2A643) + bit4(0xB2A643) + bit5(0xB2A643) + bit6(0xB2A643) +
    bit2(0xB2A644) + bit3(0xB2A644) + bit4(0xB2A644) + bit5(0xB2A644) + bit6(0xB2A644) +
    bit2(0xB2A645) + bit3(0xB2A645) + bit4(0xB2A645) + bit5(0xB2A645) + bit6(0xB2A645) +
    bit2(0xB2A646) + bit3(0xB2A646) + bit4(0xB2A646) + bit5(0xB2A646) + bit6(0xB2A646) +
    bit2(0xB2A647) + bit3(0xB2A647) + bit4(0xB2A647) + bit5(0xB2A647) + bit6(0xB2A647) +
    bit2(0xB2A648) + bit3(0xB2A648) + bit4(0xB2A648) + bit5(0xB2A648) + bit6(0xB2A648) +
    bit2(0xB2A649) + bit3(0xB2A649) + bit4(0xB2A649) + bit5(0xB2A649) + bit6(0xB2A649) +
    bit2(0xB2A64A) + bit3(0xB2A64A) + bit4(0xB2A64A) + bit5(0xB2A64A) + bit6(0xB2A64A) +
    bit2(0xB2A64B) + bit3(0xB2A64B) + bit4(0xB2A64B) + bit5(0xB2A64B) + bit6(0xB2A64B) +
    bit2(0xB2A64C) + bit3(0xB2A64C) + bit4(0xB2A64C) + bit5(0xB2A64C) + bit6(0xB2A64C) +
    bit2(0xB2A64D) + bit3(0xB2A64D) + bit4(0xB2A64D) + bit5(0xB2A64D) + bit6(0xB2A64D) +
    bit2(0xB2A64E) + bit3(0xB2A64E) + bit4(0xB2A64E) + bit5(0xB2A64E) + bit6(0xB2A64E) +
    bit2(0xB2A64F) + bit3(0xB2A64F) + bit4(0xB2A64F) + bit5(0xB2A64F) + bit6(0xB2A64F) +
    bit2(0xB2A650) + bit3(0xB2A650) + bit4(0xB2A650) + bit5(0xB2A650) + bit6(0xB2A650) +
    bit2(0xB2A651) + bit3(0xB2A651) + bit4(0xB2A651) + bit6(0xB2A651) +
    bit2(0xB2A652) + bit3(0xB2A652) + bit4(0xB2A652) + bit6(0xB2A652) +
    bit2(0xB2A653) + bit3(0xB2A653) + bit4(0xB2A653) + bit5(0xB2A653) + bit6(0xB2A653) +
    bit2(0xB2A654) + bit3(0xB2A654) + bit4(0xB2A654) + bit6(0xB2A654) +
    bit2(0xB2A655) + bit3(0xB2A655) + bit4(0xB2A655) + bit6(0xB2A655) +
    bit2(0xB2A656) + bit3(0xB2A656) + bit4(0xB2A656) + bit5(0xB2A656) + bit6(0xB2A656) +
    bit2(0xB2A657) + bit3(0xB2A657) + bit4(0xB2A657) + bit5(0xB2A657) + bit6(0xB2A657) +
    bit2(0xB2A658) + bit3(0xB2A658) + bit4(0xB2A658) + bit5(0xB2A658) + bit6(0xB2A658) +
    bit2(0xB2A659) + bit3(0xB2A659) + bit4(0xB2A659) + bit5(0xB2A659) + bit6(0xB2A659) +
    bit2(0xB2A65A) + bit3(0xB2A65A) + bit4(0xB2A65A) + bit5(0xB2A65A) + bit6(0xB2A65A) +
    bit2(0xB2A65B) + bit3(0xB2A65B) + bit4(0xB2A65B) + bit5(0xB2A65B) + bit6(0xB2A65B) +
    bit2(0xB2A65C) + bit3(0xB2A65C) + bit4(0xB2A65C) + bit5(0xB2A65C) + bit6(0xB2A65C) +
    bit2(0xB2A65D) + bit3(0xB2A65D) + bit4(0xB2A65D) + bit5(0xB2A65D) + bit6(0xB2A65D) +
    bit2(0xB2A65E) + bit3(0xB2A65E) + bit4(0xB2A65E) + bit5(0xB2A65E) + bit6(0xB2A65E) +
    bit2(0xB2A65F) + bit3(0xB2A65F) + bit4(0xB2A65F) + bit5(0xB2A65F) + bit6(0xB2A65F) +
    bit2(0xB2A660) + bit3(0xB2A660) + bit4(0xB2A660) + bit5(0xB2A660) + bit6(0xB2A660) +
    bit2(0xB2A661) + bit3(0xB2A661) + bit4(0xB2A661) + bit5(0xB2A661) + bit6(0xB2A661) +
    bit2(0xB2A662) + bit3(0xB2A662) + bit4(0xB2A662) + bit5(0xB2A662) + bit6(0xB2A662) +
    bit2(0xB2A663) + bit3(0xB2A663) + bit4(0xB2A663) + bit5(0xB2A663) + bit6(0xB2A663) +
    bit2(0xB2A664) + bit3(0xB2A664) + bit4(0xB2A664) + bit5(0xB2A664) + bit6(0xB2A664) +
    bit2(0xB2A665) + bit3(0xB2A665) + bit4(0xB2A665) + bit6(0xB2A665) +
    bit2(0xB2A666) + bit3(0xB2A666) + bit4(0xB2A666) + bit6(0xB2A666) +
    bit2(0xB2A667) + bit3(0xB2A667) + bit4(0xB2A667) + bit6(0xB2A667) +
    bit2(0xB2A668) + bit3(0xB2A668) + bit4(0xB2A668) + bit6(0xB2A668) +
    bit2(0xB2A669) + bit3(0xB2A669) + bit4(0xB2A669) + bit6(0xB2A669) +
    bit2(0xB2A66A) + bit3(0xB2A66A) + bit4(0xB2A66A) + bit6(0xB2A66A) +
    bit2(0xB2A66B) + bit3(0xB2A66B) + bit4(0xB2A66B) + bit6(0xB2A66B) +
    bit2(0xB2A66C) + bit3(0xB2A66C) + bit4(0xB2A66C) + bit5(0xB2A66C) + bit6(0xB2A66C) +
    bit2(0xB2A66D) + bit3(0xB2A66D) + bit4(0xB2A66D) + bit6(0xB2A66D) +
    bit2(0xB2A66E) + bit3(0xB2A66E) + bit4(0xB2A66E) + bit6(0xB2A66E) +
    bit2(0xB2A66F) + bit3(0xB2A66F) + bit4(0xB2A66F) + bit6(0xB2A66F) +
    bit2(0xB2A670) + bit3(0xB2A670) + bit4(0xB2A670) + bit6(0xB2A670) +
    bit2(0xB2A671) + bit3(0xB2A671) + bit4(0xB2A671) + bit6(0xB2A671) +
    bit2(0xB2A672) + bit3(0xB2A672) + bit4(0xB2A672) + bit5(0xB2A672) + bit6(0xB2A672) +
    bit2(0xB2A673) + bit3(0xB2A673) + bit4(0xB2A673) + bit5(0xB2A673) + bit6(0xB2A673) +
    bit2(0xB2A674) + bit3(0xB2A674) + bit4(0xB2A674) + bit5(0xB2A674) + bit6(0xB2A674) +
    bit2(0xB2A675) + bit3(0xB2A675) + bit4(0xB2A675) + bit5(0xB2A675) + bit6(0xB2A675) +
    bit2(0xB2A676) + bit3(0xB2A676) + bit4(0xB2A676) + bit5(0xB2A676) + bit6(0xB2A676) +
    bit2(0xB2A677) + bit3(0xB2A677) + bit4(0xB2A677) + bit5(0xB2A677) + bit6(0xB2A677) +
    bit2(0xB2A678) + bit3(0xB2A678) + bit4(0xB2A678) + bit5(0xB2A678) + bit6(0xB2A678) +
    bit2(0xB2A679) + bit3(0xB2A679) + bit4(0xB2A679) + bit6(0xB2A679) +
    bit2(0xB2A67A) + bit3(0xB2A67A) + bit4(0xB2A67A) + bit5(0xB2A67A) + bit6(0xB2A67A) +
    bit2(0xB2A67B) + bit3(0xB2A67B) + bit4(0xB2A67B) + bit5(0xB2A67B) + bit6(0xB2A67B) +
    bit2(0xB2A67C) + bit3(0xB2A67C) + bit4(0xB2A67C) + bit5(0xB2A67C) + bit6(0xB2A67C) +
    bit2(0xB2A67D) + bit3(0xB2A67D) + bit4(0xB2A67D) + bit5(0xB2A67D) + bit6(0xB2A67D) +
    bit2(0xB2A67E) + bit3(0xB2A67E) + bit4(0xB2A67E) + bit5(0xB2A67E) + bit6(0xB2A67E) +
    bit2(0xB2A67F) + bit3(0xB2A67F) + bit4(0xB2A67F) + bit5(0xB2A67F) + bit6(0xB2A67F) +
    bit2(0xB2A680) + bit3(0xB2A680) + bit4(0xB2A680) + bit5(0xB2A680) + bit6(0xB2A680) +
    bit2(0xB2A681) + bit3(0xB2A681) + bit4(0xB2A681) + bit5(0xB2A681) + bit6(0xB2A681) +
    bit2(0xB2A682) + bit3(0xB2A682) + bit4(0xB2A682) + bit5(0xB2A682) + bit6(0xB2A682) +
    bit2(0xB2A683) + bit3(0xB2A683) + bit4(0xB2A683) + bit6(0xB2A683) +
    bit2(0xB2A684) + bit3(0xB2A684) + bit4(0xB2A684) + bit5(0xB2A684) + bit6(0xB2A684) +
    bit2(0xB2A685) + bit3(0xB2A685) + bit4(0xB2A685) + bit5(0xB2A685) + bit6(0xB2A685) +
    bit2(0xB2A686) + bit3(0xB2A686) + bit4(0xB2A686) + bit5(0xB2A686) + bit6(0xB2A686) +
    bit2(0xB2A687) + bit3(0xB2A687) + bit4(0xB2A687) + bit6(0xB2A687) +
    bit2(0xB2A688) + bit3(0xB2A688) + bit4(0xB2A688) + bit6(0xB2A688) +
    bit2(0xB2A689) + bit3(0xB2A689) + bit4(0xB2A689) + bit6(0xB2A689) +
    bit2(0xB2A68A) + bit3(0xB2A68A) + bit4(0xB2A68A) + bit6(0xB2A68A) +
    bit2(0xB2A68B) + bit3(0xB2A68B) + bit4(0xB2A68B) + bit5(0xB2A68B) + bit6(0xB2A68B) +
    bit2(0xB2A68C) + bit3(0xB2A68C) + bit4(0xB2A68C) + bit5(0xB2A68C) + bit6(0xB2A68C) +
    bit2(0xB2A68D) + bit3(0xB2A68D) + bit4(0xB2A68D) + bit5(0xB2A68D) + bit6(0xB2A68D) +
    bit2(0xB2A68E) + bit3(0xB2A68E) + bit4(0xB2A68E) + bit5(0xB2A68E) + bit6(0xB2A68E) +
    bit2(0xB2A68F) + bit3(0xB2A68F) + bit4(0xB2A68F) + bit5(0xB2A68F) + bit6(0xB2A68F) +
    bit2(0xB2A690) + bit3(0xB2A690) + bit4(0xB2A690) + bit5(0xB2A690) + bit6(0xB2A690) +
    bit2(0xB2A691) + bit3(0xB2A691) + bit4(0xB2A691) + bit5(0xB2A691) + bit6(0xB2A691) +
    bit2(0xB2A692) + bit3(0xB2A692) + bit4(0xB2A692) + bit5(0xB2A692) + bit6(0xB2A692) +
    bit2(0xB2A693) + bit3(0xB2A693) + bit4(0xB2A693) + bit6(0xB2A693) +
    bit2(0xB2A694) + bit3(0xB2A694) + bit4(0xB2A694) + bit5(0xB2A694) + bit6(0xB2A694) +
    bit2(0xB2A695) + bit3(0xB2A695) + bit4(0xB2A695) + bit6(0xB2A695) +
    bit2(0xB2A696) + bit3(0xB2A696) + bit4(0xB2A696) + bit6(0xB2A696) +
    bit2(0xB2A697) + bit3(0xB2A697) + bit4(0xB2A697) + bit6(0xB2A697) +
    bit2(0xB2A698) + bit3(0xB2A698) + bit4(0xB2A698) + bit5(0xB2A698) + bit6(0xB2A698) +
    bit2(0xB2A699) + bit3(0xB2A699) + bit4(0xB2A699) + bit5(0xB2A699) + bit6(0xB2A699) +
    bit2(0xB2A69A) + bit3(0xB2A69A) + bit4(0xB2A69A) + bit5(0xB2A69A) + bit6(0xB2A69A) +
    bit2(0xB2A69B) + bit3(0xB2A69B) + bit4(0xB2A69B) + bit5(0xB2A69B) + bit6(0xB2A69B) +
    bit2(0xB2A69C) + bit3(0xB2A69C) + bit4(0xB2A69C) + bit6(0xB2A69C) +
    bit2(0xB2A69D) + bit3(0xB2A69D) + bit4(0xB2A69D) + bit6(0xB2A69D) +
    bit2(0xB2A69E) + bit3(0xB2A69E) + bit4(0xB2A69E) + bit5(0xB2A69E) + bit6(0xB2A69E) +
    bit2(0xB2A69F) + bit3(0xB2A69F) + bit4(0xB2A69F) + bit5(0xB2A69F) + bit6(0xB2A69F) +
    bit2(0xB2A6A0) + bit3(0xB2A6A0) + bit4(0xB2A6A0) + bit6(0xB2A6A0) +
    bit2(0xB2A6A1) + bit3(0xB2A6A1) + bit4(0xB2A6A1) + bit6(0xB2A6A1) +
    bit2(0xB2A6A2) + bit3(0xB2A6A2) + bit4(0xB2A6A2) + bit6(0xB2A6A2) +
    bit2(0xB2A6A3) + bit3(0xB2A6A3) + bit4(0xB2A6A3) + bit5(0xB2A6A3) + bit6(0xB2A6A3) +
    bit2(0xB2A6A4) + bit4(0xB2A6A4) +
    bit2(0xB2A6A5) + bit4(0xB2A6A5) +
    bit2(0xB2A6A6) + bit4(0xB2A6A6) +
    bit2(0xB2A6A8) + bit3(0xB2A6A8) + bit6(0xB2A6A8) +
    bit2(0xB2A6A9) + bit3(0xB2A6A9) + bit6(0xB2A6A9) +
    bit2(0xB2A6AA) + bit3(0xB2A6AA) + bit6(0xB2A6AA) +
    bit2(0xB2A6AB) + bit4(0xB2A6AB) + bit5(0xB2A6AB) +
    bit2(0xB2A6B3) + bit4(0xB2A6B3) +
    bit2(0xB2A6B4) + bit4(0xB2A6B4) +
    bit2(0xB2A6B5) + bit4(0xB2A6B5) +
    bit2(0xB2A6B6) + bit4(0xB2A6B6) +
    bit2(0xB2A6C0) + bit4(0xB2A6C0) +
    bit2(0xB2A6C2) + bit4(0xB2A6C2) +
    bit2(0xB2A6C3) + bit4(0xB2A6C3) +
    bit2(0xB2A6C4) + bit3(0xB2A6C4) +
    bit2(0xB2A6C5) + bit3(0xB2A6C5) +
    bit2(0xB2A6C6) + bit4(0xB2A6C6) +
    bit2(0xB2A6C7) + 
    bit2(0xB2A6C9) + bit4(0xB2A6C9) + bit5(0xB2A6C9) +
    bit2(0xB2A6CA) + bit3(0xB2A6CA) + bit4(0xB2A6CA) + bit5(0xB2A6CA) + bit6(0xB2A6CA) +
    bit2(0xB2A6CB) + bit4(0xB2A6CB) + bit5(0xB2A6CB) +
    bit2(0xB2A6CC) + bit4(0xB2A6CC) +
    bit2(0xB2A6CD) + bit4(0xB2A6CD) +
    bit2(0xB2A6CE) + bit4(0xB2A6CE) +
    bit2(0xB2A6CF) + bit4(0xB2A6CF) +
    bit2(0xB2A6D0) + bit4(0xB2A6D0) +
    bit2(0xB2A6D1) + bit4(0xB2A6D1) +
    bit2(0xB2A6D2) + bit4(0xB2A6D2) +
    bit2(0xB2A6D3) + bit4(0xB2A6D3) +
    bit2(0xB2A6D4) + bit4(0xB2A6D4) +
    bit2(0xB2A6D5) + bit4(0xB2A6D5) +
    bit2(0xB2A6D6) + bit4(0xB2A6D6) +
    bit2(0xB2A6D7) + bit4(0xB2A6D7) +
    bit2(0xB2A6D8) + bit4(0xB2A6D8) +
    bit2(0xB2A6D9) + bit4(0xB2A6D9) +
    bit2(0xB2A6DA) + bit4(0xB2A6DA) +
    bit2(0xB2A6DB) + bit4(0xB2A6DB) +
    bit2(0xB2A6DC) + bit4(0xB2A6DC)
}


achievement(
    title = "Monster Enthusiast",
    description = "Fill 25% of the Monster List.",
    points = 3,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        MonsterListProgress() >= 152 &&
        prev(MonsterListProgress()) < 152
)

achievement(
    title = "Monster Researcher",
    description = "Fill 50% of the Monster List.",
    points = 5,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        MonsterListProgress() >= 304 &&
        prev(MonsterListProgress()) < 304
)

achievement(
    title = "Monster Expert",
    description = "Fill 75% of the Monster List.",
    points = 10,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        MonsterListProgress() >= 456 &&
        prev(MonsterListProgress()) < 456
)

achievement(
    title = "Monster Encyclopedia Master",
    description = "Completely fill the Monster List.",
    points = 25,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        measured(MonsterListProgress() == 607) &&
        prev(MonsterListProgress()) < 607
)


function PeopleListCount()
{
    return
        PeopleListNoin() +
        PeopleListGray() +
        PeopleListFee() +
        PeopleListPoe() +
        PeopleListIris() +
        PeopleListKreuz() +
        PeopleListEizlenHighPriest() +
        PeopleListChaos() +
        PeopleListGalahad() +
        PeopleListTolena() +
        PeopleListTheodore() +
        PeopleListMax() +
        PeopleListYuveria() +
        PeopleListMeila() +
        PeopleListMitsue() +
        PeopleListHagel() +
        PeopleListTheresa() +
        PeopleListYach() +
        PeopleListKlavia() +
        PeopleListLutanus() +
        PeopleListMelona()
}

achievement(
    title = "People Scholar",
    description = "Record 50% of people entries.",
    points = 5,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(PeopleListCount()) < 21 &&
        PeopleListCount() >= 21
)

achievement(
    title = "Chronicler of Eden",
    description = "Record 100% of people entries.",
    points = 10,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(PeopleListCount()) < 42 &&
        measured(PeopleListCount() >= 42)
)

function ReviewListCount()
{
    return
        (ReviewListEleCostDownXs() / 0x2) +
        (ReviewListDelSupportX1() / 0x2) +
        (ReviewListQualityUpXs() / 0x2) +
        (ReviewListDamageUpXs() / 0x2) +
        (ReviewListHealUpXs() / 0x2) +
        (ReviewListLifeUpXs() / 0x2) +
        (ReviewListPwrUpXs() / 0x2) +
        (ReviewListDefUpXs() / 0x2) +
        (ReviewListMagicUpXs() / 0x2) +
        (ReviewListSpdUpXs() / 0x2) +
        (ReviewListFResUpXs() / 0x2) +
        (ReviewListIResUpXs() / 0x2) +
        (ReviewListLResUpXs() / 0x2) +
        (ReviewListDResUpXs() / 0x2) +
        (ReviewListAllResUpXs() / 0x2) +
        (ReviewListFDamageS() / 0x2) +
        (ReviewListIDamageS() / 0x2) +
        (ReviewListLDamageS() / 0x2) +
        (ReviewListDDamageS() / 0x2) +
        (ReviewListHrzRangeS() / 0x2) +
        (ReviewListVerRangeS() / 0x2) +
        (ReviewListRangeS() / 0x2) +
        (ReviewListAttack1() / 0x2) +
        (ReviewListCriticalUpS() / 0x2) +
        (ReviewListMagicCriticalUpS() / 0x2) +
        (ReviewListEleCostDownS() / 0x2) +
        (ReviewListDelSupportX2() / 0x2) +
        (ReviewListQualityUpS() / 0x2) +
        (ReviewListDamageUpS() / 0x2) +
        (ReviewListHealUpS() / 0x2) +
        (ReviewListLifeUpS() / 0x2) +
        (ReviewListPwrUpS() / 0x2) +
        (ReviewListDefUpS() / 0x2) +
        (ReviewListMagicUpS() / 0x2) +
        (ReviewListSpdUpS() / 0x2) +
        (ReviewListFResUpS() / 0x2) +
        (ReviewListIResUpS() / 0x2) +
        (ReviewListLResUpS() / 0x2) +
        (ReviewListDResUpS() / 0x2) +
        (ReviewListAllResUpS() / 0x2)
}

achievement(
    title = "Review Analyst",
    description = "Complete 50% of the review list.",
    points = 5,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(ReviewListCount()) < 64 &&
        ReviewListCount() >= 64
)

achievement(
    title = "Review Archivist",
    description = "Complete 100% of the review list.",
    points = 10,
    trigger =
    never(MemoryCardAccessor() == 0x144240) &&
        InGame() == 0x1 &&
        prev(ReviewListCount()) < 129 &&
        measured(ReviewListCount() >= 129)
)
